// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module lesion_accel_convolution_Pipeline_VITIS_LOOP_69_19_VITIS_LOOP_70_20_VITIS_LOOP_71_21 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY,
        m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY,
        m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY,
        m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID,
        m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA,
        m_axi_gmem_0_RLAST,
        m_axi_gmem_0_RID,
        m_axi_gmem_0_RFIFONUM,
        m_axi_gmem_0_RUSER,
        m_axi_gmem_0_RRESP,
        m_axi_gmem_0_BVALID,
        m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP,
        m_axi_gmem_0_BID,
        m_axi_gmem_0_BUSER,
        oc,
        co,
        h,
        ty,
        w,
        d_load_17,
        tx,
        acc_address0,
        acc_ce0,
        acc_q0,
        acc_1_address0,
        acc_1_ce0,
        acc_1_q0,
        acc_2_address0,
        acc_2_ce0,
        acc_2_q0,
        acc_3_address0,
        acc_3_ce0,
        acc_3_q0,
        acc_4_address0,
        acc_4_ce0,
        acc_4_q0,
        acc_5_address0,
        acc_5_ce0,
        acc_5_q0,
        acc_6_address0,
        acc_6_ce0,
        acc_6_q0,
        acc_7_address0,
        acc_7_ce0,
        acc_7_q0,
        d_load_14,
        d_load_15,
        icmp_ln74,
        zext_ln27,
        mem,
        grp_fu_2124_p_din0,
        grp_fu_2124_p_din1,
        grp_fu_2124_p_dout0,
        grp_fu_2124_p_ce,
        grp_rq_fu_2128_p_din1,
        grp_rq_fu_2128_p_din2,
        grp_rq_fu_2128_p_din3,
        grp_rq_fu_2128_p_din4,
        grp_rq_fu_2128_p_dout0,
        grp_rq_fu_2128_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_0_AWVALID;
input   m_axi_gmem_0_AWREADY;
output  [63:0] m_axi_gmem_0_AWADDR;
output  [0:0] m_axi_gmem_0_AWID;
output  [31:0] m_axi_gmem_0_AWLEN;
output  [2:0] m_axi_gmem_0_AWSIZE;
output  [1:0] m_axi_gmem_0_AWBURST;
output  [1:0] m_axi_gmem_0_AWLOCK;
output  [3:0] m_axi_gmem_0_AWCACHE;
output  [2:0] m_axi_gmem_0_AWPROT;
output  [3:0] m_axi_gmem_0_AWQOS;
output  [3:0] m_axi_gmem_0_AWREGION;
output  [0:0] m_axi_gmem_0_AWUSER;
output   m_axi_gmem_0_WVALID;
input   m_axi_gmem_0_WREADY;
output  [7:0] m_axi_gmem_0_WDATA;
output  [0:0] m_axi_gmem_0_WSTRB;
output   m_axi_gmem_0_WLAST;
output  [0:0] m_axi_gmem_0_WID;
output  [0:0] m_axi_gmem_0_WUSER;
output   m_axi_gmem_0_ARVALID;
input   m_axi_gmem_0_ARREADY;
output  [63:0] m_axi_gmem_0_ARADDR;
output  [0:0] m_axi_gmem_0_ARID;
output  [31:0] m_axi_gmem_0_ARLEN;
output  [2:0] m_axi_gmem_0_ARSIZE;
output  [1:0] m_axi_gmem_0_ARBURST;
output  [1:0] m_axi_gmem_0_ARLOCK;
output  [3:0] m_axi_gmem_0_ARCACHE;
output  [2:0] m_axi_gmem_0_ARPROT;
output  [3:0] m_axi_gmem_0_ARQOS;
output  [3:0] m_axi_gmem_0_ARREGION;
output  [0:0] m_axi_gmem_0_ARUSER;
input   m_axi_gmem_0_RVALID;
output   m_axi_gmem_0_RREADY;
input  [7:0] m_axi_gmem_0_RDATA;
input   m_axi_gmem_0_RLAST;
input  [0:0] m_axi_gmem_0_RID;
input  [12:0] m_axi_gmem_0_RFIFONUM;
input  [0:0] m_axi_gmem_0_RUSER;
input  [1:0] m_axi_gmem_0_RRESP;
input   m_axi_gmem_0_BVALID;
output   m_axi_gmem_0_BREADY;
input  [1:0] m_axi_gmem_0_BRESP;
input  [0:0] m_axi_gmem_0_BID;
input  [0:0] m_axi_gmem_0_BUSER;
input  [30:0] oc;
input  [31:0] co;
input  [31:0] h;
input  [30:0] ty;
input  [31:0] w;
input  [31:0] d_load_17;
input  [30:0] tx;
output  [5:0] acc_address0;
output   acc_ce0;
input  [31:0] acc_q0;
output  [5:0] acc_1_address0;
output   acc_1_ce0;
input  [31:0] acc_1_q0;
output  [5:0] acc_2_address0;
output   acc_2_ce0;
input  [31:0] acc_2_q0;
output  [5:0] acc_3_address0;
output   acc_3_ce0;
input  [31:0] acc_3_q0;
output  [5:0] acc_4_address0;
output   acc_4_ce0;
input  [31:0] acc_4_q0;
output  [5:0] acc_5_address0;
output   acc_5_ce0;
input  [31:0] acc_5_q0;
output  [5:0] acc_6_address0;
output   acc_6_ce0;
input  [31:0] acc_6_q0;
output  [5:0] acc_7_address0;
output   acc_7_ce0;
input  [31:0] acc_7_q0;
input  [31:0] d_load_14;
input  [31:0] d_load_15;
input  [0:0] icmp_ln74;
input  [30:0] zext_ln27;
input  [63:0] mem;
output  [31:0] grp_fu_2124_p_din0;
output  [31:0] grp_fu_2124_p_din1;
input  [31:0] grp_fu_2124_p_dout0;
output   grp_fu_2124_p_ce;
output  [31:0] grp_rq_fu_2128_p_din1;
output  [31:0] grp_rq_fu_2128_p_din2;
output  [31:0] grp_rq_fu_2128_p_din3;
output  [0:0] grp_rq_fu_2128_p_din4;
input  [7:0] grp_rq_fu_2128_p_dout0;
output   grp_rq_fu_2128_p_ce;

reg ap_idle;
reg m_axi_gmem_0_AWVALID;
reg m_axi_gmem_0_WVALID;
reg m_axi_gmem_0_BREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_idle_pp0;
reg   [0:0] and_ln73_1_reg_870;
reg   [0:0] and_ln73_1_reg_870_pp0_iter10_reg;
reg    ap_block_state12_io_grp1;
reg   [0:0] and_ln73_1_reg_870_pp0_iter11_reg;
reg    ap_block_state13_io_grp1;
reg   [0:0] and_ln73_1_reg_870_pp0_iter16_reg;
reg    ap_block_state18_pp0_stage0_iter17_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln69_fu_415_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_blk_n_AW;
wire    ap_block_pp0_stage0_grp1;
reg    gmem_blk_n_W;
reg    gmem_blk_n_B;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [63:0] zext_ln27_cast_fu_368_p1;
reg   [63:0] zext_ln27_cast_reg_804;
wire   [31:0] tx_cast_fu_372_p1;
reg   [31:0] tx_cast_reg_809;
wire   [31:0] ty_cast_fu_376_p1;
reg   [31:0] ty_cast_reg_814;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln70_fu_436_p2;
reg   [0:0] icmp_ln70_reg_824;
wire   [2:0] trunc_ln69_fu_454_p1;
reg   [2:0] trunc_ln69_reg_831;
reg   [2:0] trunc_ln69_reg_831_pp0_iter1_reg;
reg   [2:0] trunc_ln69_reg_831_pp0_iter2_reg;
wire  signed [31:0] add_ln73_fu_458_p2;
reg  signed [31:0] add_ln73_reg_836;
wire   [3:0] x_5_mid2_fu_534_p3;
reg   [3:0] x_5_mid2_reg_842;
reg   [3:0] x_5_mid2_reg_842_pp0_iter2_reg;
reg   [3:0] x_5_mid2_reg_842_pp0_iter3_reg;
reg   [3:0] x_5_mid2_reg_842_pp0_iter4_reg;
reg   [3:0] x_5_mid2_reg_842_pp0_iter5_reg;
wire   [3:0] select_ln70_fu_542_p3;
reg   [3:0] select_ln70_reg_849;
wire   [0:0] icmp_ln73_fu_550_p2;
reg   [0:0] icmp_ln73_reg_854;
wire   [2:0] trunc_ln74_fu_554_p1;
reg   [2:0] trunc_ln74_reg_859;
reg   [2:0] trunc_ln74_reg_859_pp0_iter2_reg;
reg   [31:0] mul_ln74_reg_865;
wire   [0:0] and_ln73_1_fu_615_p2;
reg   [0:0] and_ln73_1_reg_870_pp0_iter3_reg;
reg   [0:0] and_ln73_1_reg_870_pp0_iter4_reg;
reg   [0:0] and_ln73_1_reg_870_pp0_iter5_reg;
reg   [0:0] and_ln73_1_reg_870_pp0_iter6_reg;
reg   [0:0] and_ln73_1_reg_870_pp0_iter7_reg;
reg   [0:0] and_ln73_1_reg_870_pp0_iter8_reg;
reg   [0:0] and_ln73_1_reg_870_pp0_iter9_reg;
reg   [0:0] and_ln73_1_reg_870_pp0_iter12_reg;
reg   [0:0] and_ln73_1_reg_870_pp0_iter13_reg;
reg   [0:0] and_ln73_1_reg_870_pp0_iter14_reg;
reg   [0:0] and_ln73_1_reg_870_pp0_iter15_reg;
wire  signed [31:0] add_ln74_1_fu_646_p2;
reg  signed [31:0] add_ln74_1_reg_914;
wire   [31:0] tmp_fu_652_p19;
reg   [31:0] tmp_reg_919;
wire   [31:0] grp_fu_364_p2;
reg   [31:0] mul_ln74_1_reg_924;
wire   [32:0] add_ln74_5_fu_702_p2;
reg   [32:0] add_ln74_5_reg_929;
reg   [63:0] gmem_addr_reg_934;
reg   [63:0] gmem_addr_reg_934_pp0_iter8_reg;
reg   [63:0] gmem_addr_reg_934_pp0_iter9_reg;
reg   [63:0] gmem_addr_reg_934_pp0_iter10_reg;
reg   [7:0] tmp_3_reg_941;
reg    ap_block_state18_pp0_stage0_iter17_ignore_call19_grp1;
reg    ap_block_pp0_stage0_11001_ignoreCallOp145_grp1;
reg    grp_rq_fu_352_ap_ce;
reg    ap_block_pp0_stage0_11001_ignoreCallOp126_grp1;
wire    ap_block_pp0_stage0_ignoreCallOp126_grp1;
wire   [63:0] zext_ln74_1_fu_627_p1;
wire   [63:0] add_ln74_6_fu_715_p2;
reg    ap_block_pp0_stage0_01001_grp1;
reg   [3:0] x_fu_136;
wire   [3:0] add_ln71_fu_558_p2;
wire    ap_loop_init;
reg   [3:0] y_7_fu_140;
reg   [7:0] indvar_flatten117_fu_144;
wire   [7:0] select_ln70_1_fu_470_p3;
reg   [7:0] ap_sig_allocacmp_indvar_flatten117_load;
wire    ap_block_pp0_stage0;
reg   [3:0] o_fu_148;
wire   [3:0] select_ln69_1_fu_442_p3;
reg   [3:0] ap_sig_allocacmp_o_load;
reg   [9:0] indvar_flatten130_fu_152;
wire   [9:0] add_ln69_1_fu_421_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten130_load;
reg    acc_ce0_local;
reg    acc_1_ce0_local;
reg    acc_2_ce0_local;
reg    acc_3_ce0_local;
reg    acc_4_ce0_local;
reg    acc_5_ce0_local;
reg    acc_6_ce0_local;
reg    acc_7_ce0_local;
wire   [3:0] add_ln69_fu_430_p2;
wire   [31:0] zext_ln69_fu_450_p1;
wire   [31:0] oc_cast_fu_380_p1;
wire   [7:0] add_ln70_1_fu_464_p2;
wire   [0:0] icmp_ln71_fu_511_p2;
wire   [0:0] xor_ln69_fu_506_p2;
wire   [3:0] select_ln69_fu_499_p3;
wire   [0:0] and_ln69_fu_517_p2;
wire   [0:0] empty_fu_529_p2;
wire   [3:0] add_ln70_fu_523_p2;
wire   [31:0] zext_ln70_fu_574_p1;
wire   [31:0] add_ln73_1_fu_577_p2;
wire  signed [31:0] icmp_ln73_1_fu_582_p1;
wire   [31:0] zext_ln71_2_fu_597_p1;
wire   [31:0] add_ln73_2_fu_600_p2;
wire  signed [31:0] icmp_ln73_2_fu_605_p1;
wire   [0:0] icmp_ln73_2_fu_605_p2;
wire   [0:0] and_ln73_fu_610_p2;
wire   [0:0] icmp_ln73_1_fu_582_p2;
wire   [5:0] zext_ln71_1_fu_594_p1;
wire   [5:0] shl_ln_fu_587_p3;
wire   [5:0] add_ln74_3_fu_621_p2;
wire   [31:0] add_ln74_fu_639_p2;
wire   [31:0] zext_ln74_fu_643_p1;
wire   [31:0] tmp_fu_652_p17;
wire   [31:0] add_ln74_2_fu_691_p2;
wire   [32:0] zext_ln71_fu_699_p1;
wire  signed [32:0] sext_ln71_fu_695_p1;
wire  signed [63:0] sext_ln74_fu_712_p1;
wire   [63:0] add_ln74_4_fu_708_p2;
reg    grp_fu_360_ce;
reg    grp_fu_364_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [2:0] tmp_fu_652_p1;
wire   [2:0] tmp_fu_652_p3;
wire   [2:0] tmp_fu_652_p5;
wire   [2:0] tmp_fu_652_p7;
wire  signed [2:0] tmp_fu_652_p9;
wire  signed [2:0] tmp_fu_652_p11;
wire  signed [2:0] tmp_fu_652_p13;
wire  signed [2:0] tmp_fu_652_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 x_fu_136 = 4'd0;
#0 y_7_fu_140 = 4'd0;
#0 indvar_flatten117_fu_144 = 8'd0;
#0 o_fu_148 = 4'd0;
#0 indvar_flatten130_fu_152 = 10'd0;
#0 ap_done_reg = 1'b0;
end

lesion_accel_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U302(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w),
    .din1(add_ln74_1_reg_914),
    .ce(grp_fu_364_ce),
    .dout(grp_fu_364_p2)
);

(* dissolve_hierarchy = "yes" *) lesion_accel_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U303(
    .din0(acc_q0),
    .din1(acc_1_q0),
    .din2(acc_2_q0),
    .din3(acc_3_q0),
    .din4(acc_4_q0),
    .din5(acc_5_q0),
    .din6(acc_6_q0),
    .din7(acc_7_q0),
    .def(tmp_fu_652_p17),
    .sel(trunc_ln69_reg_831_pp0_iter2_reg),
    .dout(tmp_fu_652_p19)
);

lesion_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter16_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln69_fu_415_p2 == 1'd0))) begin
            indvar_flatten117_fu_144 <= select_ln70_1_fu_470_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten117_fu_144 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln69_fu_415_p2 == 1'd0))) begin
            indvar_flatten130_fu_152 <= add_ln69_1_fu_421_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten130_fu_152 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln69_fu_415_p2 == 1'd0))) begin
            o_fu_148 <= select_ln69_1_fu_442_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            o_fu_148 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_fu_136 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            x_fu_136 <= add_ln71_fu_558_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        if ((ap_loop_init == 1'b1)) begin
            y_7_fu_140 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            y_7_fu_140 <= select_ln70_fu_542_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln73_reg_836 <= add_ln73_fu_458_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln70_reg_824 <= icmp_ln70_fu_436_p2;
        trunc_ln69_reg_831 <= trunc_ln69_fu_454_p1;
        trunc_ln69_reg_831_pp0_iter1_reg <= trunc_ln69_reg_831;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        add_ln74_1_reg_914 <= add_ln74_1_fu_646_p2;
        add_ln74_5_reg_929 <= add_ln74_5_fu_702_p2;
        and_ln73_1_reg_870 <= and_ln73_1_fu_615_p2;
        and_ln73_1_reg_870_pp0_iter10_reg <= and_ln73_1_reg_870_pp0_iter9_reg;
        and_ln73_1_reg_870_pp0_iter11_reg <= and_ln73_1_reg_870_pp0_iter10_reg;
        and_ln73_1_reg_870_pp0_iter12_reg <= and_ln73_1_reg_870_pp0_iter11_reg;
        and_ln73_1_reg_870_pp0_iter13_reg <= and_ln73_1_reg_870_pp0_iter12_reg;
        and_ln73_1_reg_870_pp0_iter14_reg <= and_ln73_1_reg_870_pp0_iter13_reg;
        and_ln73_1_reg_870_pp0_iter15_reg <= and_ln73_1_reg_870_pp0_iter14_reg;
        and_ln73_1_reg_870_pp0_iter16_reg <= and_ln73_1_reg_870_pp0_iter15_reg;
        and_ln73_1_reg_870_pp0_iter3_reg <= and_ln73_1_reg_870;
        and_ln73_1_reg_870_pp0_iter4_reg <= and_ln73_1_reg_870_pp0_iter3_reg;
        and_ln73_1_reg_870_pp0_iter5_reg <= and_ln73_1_reg_870_pp0_iter4_reg;
        and_ln73_1_reg_870_pp0_iter6_reg <= and_ln73_1_reg_870_pp0_iter5_reg;
        and_ln73_1_reg_870_pp0_iter7_reg <= and_ln73_1_reg_870_pp0_iter6_reg;
        and_ln73_1_reg_870_pp0_iter8_reg <= and_ln73_1_reg_870_pp0_iter7_reg;
        and_ln73_1_reg_870_pp0_iter9_reg <= and_ln73_1_reg_870_pp0_iter8_reg;
        gmem_addr_reg_934 <= add_ln74_6_fu_715_p2;
        gmem_addr_reg_934_pp0_iter10_reg <= gmem_addr_reg_934_pp0_iter9_reg;
        gmem_addr_reg_934_pp0_iter8_reg <= gmem_addr_reg_934;
        gmem_addr_reg_934_pp0_iter9_reg <= gmem_addr_reg_934_pp0_iter8_reg;
        mul_ln74_1_reg_924 <= grp_fu_364_p2;
        mul_ln74_reg_865 <= grp_fu_2124_p_dout0;
        tmp_reg_919 <= tmp_fu_652_p19;
        trunc_ln74_reg_859_pp0_iter2_reg <= trunc_ln74_reg_859;
        x_5_mid2_reg_842_pp0_iter2_reg <= x_5_mid2_reg_842;
        x_5_mid2_reg_842_pp0_iter3_reg <= x_5_mid2_reg_842_pp0_iter2_reg;
        x_5_mid2_reg_842_pp0_iter4_reg <= x_5_mid2_reg_842_pp0_iter3_reg;
        x_5_mid2_reg_842_pp0_iter5_reg <= x_5_mid2_reg_842_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        trunc_ln69_reg_831_pp0_iter2_reg <= trunc_ln69_reg_831_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        icmp_ln73_reg_854 <= icmp_ln73_fu_550_p2;
        select_ln70_reg_849 <= select_ln70_fu_542_p3;
        trunc_ln74_reg_859 <= trunc_ln74_fu_554_p1;
        tx_cast_reg_809[30 : 0] <= tx_cast_fu_372_p1[30 : 0];
        ty_cast_reg_814[30 : 0] <= ty_cast_fu_376_p1[30 : 0];
        x_5_mid2_reg_842 <= x_5_mid2_fu_534_p3;
        zext_ln27_cast_reg_804[30 : 0] <= zext_ln27_cast_fu_368_p1[30 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp145_grp1)) begin
        tmp_3_reg_941 <= grp_rq_fu_2128_p_dout0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        acc_1_ce0_local = 1'b1;
    end else begin
        acc_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        acc_2_ce0_local = 1'b1;
    end else begin
        acc_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        acc_3_ce0_local = 1'b1;
    end else begin
        acc_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        acc_4_ce0_local = 1'b1;
    end else begin
        acc_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        acc_5_ce0_local = 1'b1;
    end else begin
        acc_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        acc_6_ce0_local = 1'b1;
    end else begin
        acc_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        acc_7_ce0_local = 1'b1;
    end else begin
        acc_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        acc_ce0_local = 1'b1;
    end else begin
        acc_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln69_fu_415_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter16_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten117_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten117_load = indvar_flatten117_fu_144;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten130_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten130_load = indvar_flatten130_fu_152;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_o_load = 4'd0;
    end else begin
        ap_sig_allocacmp_o_load = o_fu_148;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1) & (1'd1 == and_ln73_1_reg_870_pp0_iter10_reg))) begin
        gmem_blk_n_AW = m_axi_gmem_0_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1) & (1'd1 == and_ln73_1_reg_870_pp0_iter16_reg))) begin
        gmem_blk_n_B = m_axi_gmem_0_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1) & (1'd1 == and_ln73_1_reg_870_pp0_iter11_reg))) begin
        gmem_blk_n_W = m_axi_gmem_0_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        grp_fu_360_ce = 1'b1;
    end else begin
        grp_fu_360_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_364_ce = 1'b1;
    end else begin
        grp_fu_364_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp126_grp1)) begin
        grp_rq_fu_352_ap_ce = 1'b1;
    end else begin
        grp_rq_fu_352_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'd1 == and_ln73_1_reg_870_pp0_iter10_reg))) begin
        m_axi_gmem_0_AWVALID = 1'b1;
    end else begin
        m_axi_gmem_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'd1 == and_ln73_1_reg_870_pp0_iter16_reg))) begin
        m_axi_gmem_0_BREADY = 1'b1;
    end else begin
        m_axi_gmem_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'd1 == and_ln73_1_reg_870_pp0_iter11_reg))) begin
        m_axi_gmem_0_WVALID = 1'b1;
    end else begin
        m_axi_gmem_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_1_address0 = zext_ln74_1_fu_627_p1;

assign acc_1_ce0 = acc_1_ce0_local;

assign acc_2_address0 = zext_ln74_1_fu_627_p1;

assign acc_2_ce0 = acc_2_ce0_local;

assign acc_3_address0 = zext_ln74_1_fu_627_p1;

assign acc_3_ce0 = acc_3_ce0_local;

assign acc_4_address0 = zext_ln74_1_fu_627_p1;

assign acc_4_ce0 = acc_4_ce0_local;

assign acc_5_address0 = zext_ln74_1_fu_627_p1;

assign acc_5_ce0 = acc_5_ce0_local;

assign acc_6_address0 = zext_ln74_1_fu_627_p1;

assign acc_6_ce0 = acc_6_ce0_local;

assign acc_7_address0 = zext_ln74_1_fu_627_p1;

assign acc_7_ce0 = acc_7_ce0_local;

assign acc_address0 = zext_ln74_1_fu_627_p1;

assign acc_ce0 = acc_ce0_local;

assign add_ln69_1_fu_421_p2 = (ap_sig_allocacmp_indvar_flatten130_load + 10'd1);

assign add_ln69_fu_430_p2 = (ap_sig_allocacmp_o_load + 4'd1);

assign add_ln70_1_fu_464_p2 = (ap_sig_allocacmp_indvar_flatten117_load + 8'd1);

assign add_ln70_fu_523_p2 = (select_ln69_fu_499_p3 + 4'd1);

assign add_ln71_fu_558_p2 = (x_5_mid2_fu_534_p3 + 4'd1);

assign add_ln73_1_fu_577_p2 = (zext_ln70_fu_574_p1 + ty_cast_reg_814);

assign add_ln73_2_fu_600_p2 = (zext_ln71_2_fu_597_p1 + tx_cast_reg_809);

assign add_ln73_fu_458_p2 = (zext_ln69_fu_450_p1 + oc_cast_fu_380_p1);

assign add_ln74_1_fu_646_p2 = (add_ln74_fu_639_p2 + zext_ln74_fu_643_p1);

assign add_ln74_2_fu_691_p2 = (d_load_17 + mul_ln74_1_reg_924);

assign add_ln74_3_fu_621_p2 = (zext_ln71_1_fu_594_p1 + shl_ln_fu_587_p3);

assign add_ln74_4_fu_708_p2 = (zext_ln27_cast_reg_804 + mem);

assign add_ln74_5_fu_702_p2 = ($signed(zext_ln71_fu_699_p1) + $signed(sext_ln71_fu_695_p1));

assign add_ln74_6_fu_715_p2 = ($signed(sext_ln74_fu_712_p1) + $signed(add_ln74_4_fu_708_p2));

assign add_ln74_fu_639_p2 = (mul_ln74_reg_865 + ty_cast_reg_814);

assign and_ln69_fu_517_p2 = (xor_ln69_fu_506_p2 & icmp_ln71_fu_511_p2);

assign and_ln73_1_fu_615_p2 = (icmp_ln73_1_fu_582_p2 & and_ln73_fu_610_p2);

assign and_ln73_fu_610_p2 = (icmp_ln73_reg_854 & icmp_ln73_2_fu_605_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b1 == ap_block_state18_pp0_stage0_iter17_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b1 == ap_block_state18_pp0_stage0_iter17_grp1)) | ((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_block_state13_io_grp1)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_io_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b1 == ap_block_state18_pp0_stage0_iter17_grp1)) | ((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_block_state13_io_grp1)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_io_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp126_grp1 = (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b1 == ap_block_state18_pp0_stage0_iter17_ignore_call19_grp1)) | ((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_block_state13_io_grp1)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_io_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp145_grp1 = (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b1 == ap_block_state18_pp0_stage0_iter17_ignore_call19_grp1)) | ((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_block_state13_io_grp1)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_io_grp1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp126_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b1 == ap_block_state18_pp0_stage0_iter17_grp1)) | ((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_block_state13_io_grp1)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_io_grp1)));
end

always @ (*) begin
    ap_block_state12_io_grp1 = ((m_axi_gmem_0_AWREADY == 1'b0) & (1'd1 == and_ln73_1_reg_870_pp0_iter10_reg));
end

always @ (*) begin
    ap_block_state13_io_grp1 = ((m_axi_gmem_0_WREADY == 1'b0) & (1'd1 == and_ln73_1_reg_870_pp0_iter11_reg));
end

always @ (*) begin
    ap_block_state18_pp0_stage0_iter17_grp1 = ((1'd1 == and_ln73_1_reg_870_pp0_iter16_reg) & (m_axi_gmem_0_BVALID == 1'b0));
end

always @ (*) begin
    ap_block_state18_pp0_stage0_iter17_ignore_call19_grp1 = ((1'd1 == and_ln73_1_reg_870_pp0_iter16_reg) & (m_axi_gmem_0_BVALID == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_fu_529_p2 = (icmp_ln70_reg_824 | and_ln69_fu_517_p2);

assign grp_fu_2124_p_ce = grp_fu_360_ce;

assign grp_fu_2124_p_din0 = add_ln73_reg_836;

assign grp_fu_2124_p_din1 = h;

assign grp_rq_fu_2128_p_ce = grp_rq_fu_352_ap_ce;

assign grp_rq_fu_2128_p_din1 = tmp_reg_919;

assign grp_rq_fu_2128_p_din2 = d_load_14;

assign grp_rq_fu_2128_p_din3 = d_load_15;

assign grp_rq_fu_2128_p_din4 = icmp_ln74;

assign icmp_ln69_fu_415_p2 = ((ap_sig_allocacmp_indvar_flatten130_load == 10'd512) ? 1'b1 : 1'b0);

assign icmp_ln70_fu_436_p2 = ((ap_sig_allocacmp_indvar_flatten117_load == 8'd64) ? 1'b1 : 1'b0);

assign icmp_ln71_fu_511_p2 = ((x_fu_136 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln73_1_fu_582_p1 = h;

assign icmp_ln73_1_fu_582_p2 = (($signed(add_ln73_1_fu_577_p2) < $signed(icmp_ln73_1_fu_582_p1)) ? 1'b1 : 1'b0);

assign icmp_ln73_2_fu_605_p1 = w;

assign icmp_ln73_2_fu_605_p2 = (($signed(add_ln73_2_fu_600_p2) < $signed(icmp_ln73_2_fu_605_p1)) ? 1'b1 : 1'b0);

assign icmp_ln73_fu_550_p2 = (($signed(add_ln73_reg_836) < $signed(co)) ? 1'b1 : 1'b0);

assign m_axi_gmem_0_ARADDR = 64'd0;

assign m_axi_gmem_0_ARBURST = 2'd0;

assign m_axi_gmem_0_ARCACHE = 4'd0;

assign m_axi_gmem_0_ARID = 1'd0;

assign m_axi_gmem_0_ARLEN = 32'd0;

assign m_axi_gmem_0_ARLOCK = 2'd0;

assign m_axi_gmem_0_ARPROT = 3'd0;

assign m_axi_gmem_0_ARQOS = 4'd0;

assign m_axi_gmem_0_ARREGION = 4'd0;

assign m_axi_gmem_0_ARSIZE = 3'd0;

assign m_axi_gmem_0_ARUSER = 1'd0;

assign m_axi_gmem_0_ARVALID = 1'b0;

assign m_axi_gmem_0_AWADDR = gmem_addr_reg_934_pp0_iter10_reg;

assign m_axi_gmem_0_AWBURST = 2'd0;

assign m_axi_gmem_0_AWCACHE = 4'd0;

assign m_axi_gmem_0_AWID = 1'd0;

assign m_axi_gmem_0_AWLEN = 64'd1;

assign m_axi_gmem_0_AWLOCK = 2'd0;

assign m_axi_gmem_0_AWPROT = 3'd0;

assign m_axi_gmem_0_AWQOS = 4'd0;

assign m_axi_gmem_0_AWREGION = 4'd0;

assign m_axi_gmem_0_AWSIZE = 3'd0;

assign m_axi_gmem_0_AWUSER = 1'd0;

assign m_axi_gmem_0_RREADY = 1'b0;

assign m_axi_gmem_0_WDATA = tmp_3_reg_941;

assign m_axi_gmem_0_WID = 1'd0;

assign m_axi_gmem_0_WLAST = 1'b0;

assign m_axi_gmem_0_WSTRB = 1'd1;

assign m_axi_gmem_0_WUSER = 1'd0;

assign oc_cast_fu_380_p1 = oc;

assign select_ln69_1_fu_442_p3 = ((icmp_ln70_fu_436_p2[0:0] == 1'b1) ? add_ln69_fu_430_p2 : ap_sig_allocacmp_o_load);

assign select_ln69_fu_499_p3 = ((icmp_ln70_reg_824[0:0] == 1'b1) ? 4'd0 : y_7_fu_140);

assign select_ln70_1_fu_470_p3 = ((icmp_ln70_fu_436_p2[0:0] == 1'b1) ? 8'd1 : add_ln70_1_fu_464_p2);

assign select_ln70_fu_542_p3 = ((and_ln69_fu_517_p2[0:0] == 1'b1) ? add_ln70_fu_523_p2 : select_ln69_fu_499_p3);

assign sext_ln71_fu_695_p1 = $signed(add_ln74_2_fu_691_p2);

assign sext_ln74_fu_712_p1 = $signed(add_ln74_5_reg_929);

assign shl_ln_fu_587_p3 = {{trunc_ln74_reg_859}, {3'd0}};

assign tmp_fu_652_p17 = 'bx;

assign trunc_ln69_fu_454_p1 = select_ln69_1_fu_442_p3[2:0];

assign trunc_ln74_fu_554_p1 = select_ln70_fu_542_p3[2:0];

assign tx_cast_fu_372_p1 = tx;

assign ty_cast_fu_376_p1 = ty;

assign x_5_mid2_fu_534_p3 = ((empty_fu_529_p2[0:0] == 1'b1) ? 4'd0 : x_fu_136);

assign xor_ln69_fu_506_p2 = (icmp_ln70_reg_824 ^ 1'd1);

assign zext_ln27_cast_fu_368_p1 = zext_ln27;

assign zext_ln69_fu_450_p1 = select_ln69_1_fu_442_p3;

assign zext_ln70_fu_574_p1 = select_ln70_reg_849;

assign zext_ln71_1_fu_594_p1 = x_5_mid2_reg_842;

assign zext_ln71_2_fu_597_p1 = x_5_mid2_reg_842;

assign zext_ln71_fu_699_p1 = x_5_mid2_reg_842_pp0_iter5_reg;

assign zext_ln74_1_fu_627_p1 = add_ln74_3_fu_621_p2;

assign zext_ln74_fu_643_p1 = trunc_ln74_reg_859_pp0_iter2_reg;

always @ (posedge ap_clk) begin
    zext_ln27_cast_reg_804[63:31] <= 33'b000000000000000000000000000000000;
    tx_cast_reg_809[31] <= 1'b0;
    ty_cast_reg_814[31] <= 1'b0;
end

endmodule //lesion_accel_convolution_Pipeline_VITIS_LOOP_69_19_VITIS_LOOP_70_20_VITIS_LOOP_71_21
