// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module lesion_accel_convolution_Pipeline_VITIS_LOOP_28_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        or_ln32_6,
        co,
        or_ln32_5,
        or_ln32_4,
        or_ln32_3,
        or_ln32_2,
        or_ln32_1,
        or_ln,
        acc_7_address0,
        acc_7_ce0,
        acc_7_we0,
        acc_7_d0,
        acc_6_address0,
        acc_6_ce0,
        acc_6_we0,
        acc_6_d0,
        acc_5_address0,
        acc_5_ce0,
        acc_5_we0,
        acc_5_d0,
        acc_4_address0,
        acc_4_ce0,
        acc_4_we0,
        acc_4_d0,
        acc_3_address0,
        acc_3_ce0,
        acc_3_we0,
        acc_3_d0,
        acc_2_address0,
        acc_2_ce0,
        acc_2_we0,
        acc_2_d0,
        acc_1_address0,
        acc_1_ce0,
        acc_1_we0,
        acc_1_d0,
        acc_address0,
        acc_ce0,
        acc_we0,
        acc_d0,
        controlmem_load,
        controlmem_load_1,
        controlmem_load_2,
        controlmem_load_3,
        controlmem_load_4,
        controlmem_load_5,
        controlmem_load_6,
        controlmem_load_7
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [30:0] or_ln32_6;
input  [31:0] co;
input  [30:0] or_ln32_5;
input  [30:0] or_ln32_4;
input  [30:0] or_ln32_3;
input  [30:0] or_ln32_2;
input  [30:0] or_ln32_1;
input  [30:0] or_ln;
output  [5:0] acc_7_address0;
output   acc_7_ce0;
output   acc_7_we0;
output  [31:0] acc_7_d0;
output  [5:0] acc_6_address0;
output   acc_6_ce0;
output   acc_6_we0;
output  [31:0] acc_6_d0;
output  [5:0] acc_5_address0;
output   acc_5_ce0;
output   acc_5_we0;
output  [31:0] acc_5_d0;
output  [5:0] acc_4_address0;
output   acc_4_ce0;
output   acc_4_we0;
output  [31:0] acc_4_d0;
output  [5:0] acc_3_address0;
output   acc_3_ce0;
output   acc_3_we0;
output  [31:0] acc_3_d0;
output  [5:0] acc_2_address0;
output   acc_2_ce0;
output   acc_2_we0;
output  [31:0] acc_2_d0;
output  [5:0] acc_1_address0;
output   acc_1_ce0;
output   acc_1_we0;
output  [31:0] acc_1_d0;
output  [5:0] acc_address0;
output   acc_ce0;
output   acc_we0;
output  [31:0] acc_d0;
input  [31:0] controlmem_load;
input  [31:0] controlmem_load_1;
input  [31:0] controlmem_load_2;
input  [31:0] controlmem_load_3;
input  [31:0] controlmem_load_4;
input  [31:0] controlmem_load_5;
input  [31:0] controlmem_load_6;
input  [31:0] controlmem_load_7;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln28_fu_361_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln28_fu_373_p1;
reg   [6:0] s_fu_78;
wire   [6:0] add_ln28_fu_367_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_s_1;
reg    acc_we0_local;
reg    acc_ce0_local;
reg    acc_1_we0_local;
wire   [31:0] select_ln32_fu_385_p3;
reg    acc_1_ce0_local;
reg    acc_2_we0_local;
wire   [31:0] select_ln32_1_fu_394_p3;
reg    acc_2_ce0_local;
reg    acc_3_we0_local;
wire   [31:0] select_ln32_2_fu_403_p3;
reg    acc_3_ce0_local;
reg    acc_4_we0_local;
wire   [31:0] select_ln32_3_fu_412_p3;
reg    acc_4_ce0_local;
reg    acc_5_we0_local;
wire   [31:0] select_ln32_4_fu_421_p3;
reg    acc_5_ce0_local;
reg    acc_6_we0_local;
wire   [31:0] select_ln32_5_fu_430_p3;
reg    acc_6_ce0_local;
reg    acc_7_we0_local;
wire   [31:0] select_ln32_6_fu_439_p3;
reg    acc_7_ce0_local;
wire   [31:0] zext_ln32_6_fu_283_p1;
wire   [31:0] zext_ln32_5_fu_293_p1;
wire   [31:0] zext_ln32_4_fu_303_p1;
wire   [31:0] zext_ln32_3_fu_313_p1;
wire   [31:0] zext_ln32_2_fu_323_p1;
wire   [31:0] zext_ln32_1_fu_333_p1;
wire   [31:0] zext_ln32_fu_343_p1;
wire   [0:0] icmp_ln32_fu_347_p2;
wire   [0:0] icmp_ln32_1_fu_337_p2;
wire   [0:0] icmp_ln32_2_fu_327_p2;
wire   [0:0] icmp_ln32_3_fu_317_p2;
wire   [0:0] icmp_ln32_4_fu_307_p2;
wire   [0:0] icmp_ln32_5_fu_297_p2;
wire   [0:0] icmp_ln32_6_fu_287_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 s_fu_78 = 7'd0;
#0 ap_done_reg = 1'b0;
end

lesion_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln28_fu_361_p2 == 1'd0)) begin
            s_fu_78 <= add_ln28_fu_367_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            s_fu_78 <= 7'd0;
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_1_ce0_local = 1'b1;
    end else begin
        acc_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln28_fu_361_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_1_we0_local = 1'b1;
    end else begin
        acc_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_2_ce0_local = 1'b1;
    end else begin
        acc_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln28_fu_361_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_2_we0_local = 1'b1;
    end else begin
        acc_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_3_ce0_local = 1'b1;
    end else begin
        acc_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln28_fu_361_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_3_we0_local = 1'b1;
    end else begin
        acc_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_4_ce0_local = 1'b1;
    end else begin
        acc_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln28_fu_361_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_4_we0_local = 1'b1;
    end else begin
        acc_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_5_ce0_local = 1'b1;
    end else begin
        acc_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln28_fu_361_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_5_we0_local = 1'b1;
    end else begin
        acc_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_6_ce0_local = 1'b1;
    end else begin
        acc_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln28_fu_361_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_6_we0_local = 1'b1;
    end else begin
        acc_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_7_ce0_local = 1'b1;
    end else begin
        acc_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln28_fu_361_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_7_we0_local = 1'b1;
    end else begin
        acc_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_ce0_local = 1'b1;
    end else begin
        acc_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln28_fu_361_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_we0_local = 1'b1;
    end else begin
        acc_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln28_fu_361_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_s_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_s_1 = s_fu_78;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_1_address0 = zext_ln28_fu_373_p1;

assign acc_1_ce0 = acc_1_ce0_local;

assign acc_1_d0 = select_ln32_fu_385_p3;

assign acc_1_we0 = acc_1_we0_local;

assign acc_2_address0 = zext_ln28_fu_373_p1;

assign acc_2_ce0 = acc_2_ce0_local;

assign acc_2_d0 = select_ln32_1_fu_394_p3;

assign acc_2_we0 = acc_2_we0_local;

assign acc_3_address0 = zext_ln28_fu_373_p1;

assign acc_3_ce0 = acc_3_ce0_local;

assign acc_3_d0 = select_ln32_2_fu_403_p3;

assign acc_3_we0 = acc_3_we0_local;

assign acc_4_address0 = zext_ln28_fu_373_p1;

assign acc_4_ce0 = acc_4_ce0_local;

assign acc_4_d0 = select_ln32_3_fu_412_p3;

assign acc_4_we0 = acc_4_we0_local;

assign acc_5_address0 = zext_ln28_fu_373_p1;

assign acc_5_ce0 = acc_5_ce0_local;

assign acc_5_d0 = select_ln32_4_fu_421_p3;

assign acc_5_we0 = acc_5_we0_local;

assign acc_6_address0 = zext_ln28_fu_373_p1;

assign acc_6_ce0 = acc_6_ce0_local;

assign acc_6_d0 = select_ln32_5_fu_430_p3;

assign acc_6_we0 = acc_6_we0_local;

assign acc_7_address0 = zext_ln28_fu_373_p1;

assign acc_7_ce0 = acc_7_ce0_local;

assign acc_7_d0 = select_ln32_6_fu_439_p3;

assign acc_7_we0 = acc_7_we0_local;

assign acc_address0 = zext_ln28_fu_373_p1;

assign acc_ce0 = acc_ce0_local;

assign acc_d0 = controlmem_load;

assign acc_we0 = acc_we0_local;

assign add_ln28_fu_367_p2 = (ap_sig_allocacmp_s_1 + 7'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln28_fu_361_p2 = ((ap_sig_allocacmp_s_1 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln32_1_fu_337_p2 = (($signed(zext_ln32_1_fu_333_p1) < $signed(co)) ? 1'b1 : 1'b0);

assign icmp_ln32_2_fu_327_p2 = (($signed(zext_ln32_2_fu_323_p1) < $signed(co)) ? 1'b1 : 1'b0);

assign icmp_ln32_3_fu_317_p2 = (($signed(zext_ln32_3_fu_313_p1) < $signed(co)) ? 1'b1 : 1'b0);

assign icmp_ln32_4_fu_307_p2 = (($signed(zext_ln32_4_fu_303_p1) < $signed(co)) ? 1'b1 : 1'b0);

assign icmp_ln32_5_fu_297_p2 = (($signed(zext_ln32_5_fu_293_p1) < $signed(co)) ? 1'b1 : 1'b0);

assign icmp_ln32_6_fu_287_p2 = (($signed(zext_ln32_6_fu_283_p1) < $signed(co)) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_347_p2 = (($signed(zext_ln32_fu_343_p1) < $signed(co)) ? 1'b1 : 1'b0);

assign select_ln32_1_fu_394_p3 = ((icmp_ln32_1_fu_337_p2[0:0] == 1'b1) ? controlmem_load_2 : 32'd0);

assign select_ln32_2_fu_403_p3 = ((icmp_ln32_2_fu_327_p2[0:0] == 1'b1) ? controlmem_load_3 : 32'd0);

assign select_ln32_3_fu_412_p3 = ((icmp_ln32_3_fu_317_p2[0:0] == 1'b1) ? controlmem_load_4 : 32'd0);

assign select_ln32_4_fu_421_p3 = ((icmp_ln32_4_fu_307_p2[0:0] == 1'b1) ? controlmem_load_5 : 32'd0);

assign select_ln32_5_fu_430_p3 = ((icmp_ln32_5_fu_297_p2[0:0] == 1'b1) ? controlmem_load_6 : 32'd0);

assign select_ln32_6_fu_439_p3 = ((icmp_ln32_6_fu_287_p2[0:0] == 1'b1) ? controlmem_load_7 : 32'd0);

assign select_ln32_fu_385_p3 = ((icmp_ln32_fu_347_p2[0:0] == 1'b1) ? controlmem_load_1 : 32'd0);

assign zext_ln28_fu_373_p1 = ap_sig_allocacmp_s_1;

assign zext_ln32_1_fu_333_p1 = or_ln32_1;

assign zext_ln32_2_fu_323_p1 = or_ln32_2;

assign zext_ln32_3_fu_313_p1 = or_ln32_3;

assign zext_ln32_4_fu_303_p1 = or_ln32_4;

assign zext_ln32_5_fu_293_p1 = or_ln32_5;

assign zext_ln32_6_fu_283_p1 = or_ln32_6;

assign zext_ln32_fu_343_p1 = or_ln;

endmodule //lesion_accel_convolution_Pipeline_VITIS_LOOP_28_4
