// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module lesion_accel_lesion_accel_Pipeline_VITIS_LOOP_160_24 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_controlmem_0_AWVALID,
        m_axi_controlmem_0_AWREADY,
        m_axi_controlmem_0_AWADDR,
        m_axi_controlmem_0_AWID,
        m_axi_controlmem_0_AWLEN,
        m_axi_controlmem_0_AWSIZE,
        m_axi_controlmem_0_AWBURST,
        m_axi_controlmem_0_AWLOCK,
        m_axi_controlmem_0_AWCACHE,
        m_axi_controlmem_0_AWPROT,
        m_axi_controlmem_0_AWQOS,
        m_axi_controlmem_0_AWREGION,
        m_axi_controlmem_0_AWUSER,
        m_axi_controlmem_0_WVALID,
        m_axi_controlmem_0_WREADY,
        m_axi_controlmem_0_WDATA,
        m_axi_controlmem_0_WSTRB,
        m_axi_controlmem_0_WLAST,
        m_axi_controlmem_0_WID,
        m_axi_controlmem_0_WUSER,
        m_axi_controlmem_0_ARVALID,
        m_axi_controlmem_0_ARREADY,
        m_axi_controlmem_0_ARADDR,
        m_axi_controlmem_0_ARID,
        m_axi_controlmem_0_ARLEN,
        m_axi_controlmem_0_ARSIZE,
        m_axi_controlmem_0_ARBURST,
        m_axi_controlmem_0_ARLOCK,
        m_axi_controlmem_0_ARCACHE,
        m_axi_controlmem_0_ARPROT,
        m_axi_controlmem_0_ARQOS,
        m_axi_controlmem_0_ARREGION,
        m_axi_controlmem_0_ARUSER,
        m_axi_controlmem_0_RVALID,
        m_axi_controlmem_0_RREADY,
        m_axi_controlmem_0_RDATA,
        m_axi_controlmem_0_RLAST,
        m_axi_controlmem_0_RID,
        m_axi_controlmem_0_RFIFONUM,
        m_axi_controlmem_0_RUSER,
        m_axi_controlmem_0_RRESP,
        m_axi_controlmem_0_BVALID,
        m_axi_controlmem_0_BREADY,
        m_axi_controlmem_0_BRESP,
        m_axi_controlmem_0_BID,
        m_axi_controlmem_0_BUSER,
        sext_ln160,
        sums,
        sums_1,
        sums_2,
        sums_3,
        sums_4,
        sums_5
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_controlmem_0_AWVALID;
input   m_axi_controlmem_0_AWREADY;
output  [63:0] m_axi_controlmem_0_AWADDR;
output  [0:0] m_axi_controlmem_0_AWID;
output  [31:0] m_axi_controlmem_0_AWLEN;
output  [2:0] m_axi_controlmem_0_AWSIZE;
output  [1:0] m_axi_controlmem_0_AWBURST;
output  [1:0] m_axi_controlmem_0_AWLOCK;
output  [3:0] m_axi_controlmem_0_AWCACHE;
output  [2:0] m_axi_controlmem_0_AWPROT;
output  [3:0] m_axi_controlmem_0_AWQOS;
output  [3:0] m_axi_controlmem_0_AWREGION;
output  [0:0] m_axi_controlmem_0_AWUSER;
output   m_axi_controlmem_0_WVALID;
input   m_axi_controlmem_0_WREADY;
output  [31:0] m_axi_controlmem_0_WDATA;
output  [3:0] m_axi_controlmem_0_WSTRB;
output   m_axi_controlmem_0_WLAST;
output  [0:0] m_axi_controlmem_0_WID;
output  [0:0] m_axi_controlmem_0_WUSER;
output   m_axi_controlmem_0_ARVALID;
input   m_axi_controlmem_0_ARREADY;
output  [63:0] m_axi_controlmem_0_ARADDR;
output  [0:0] m_axi_controlmem_0_ARID;
output  [31:0] m_axi_controlmem_0_ARLEN;
output  [2:0] m_axi_controlmem_0_ARSIZE;
output  [1:0] m_axi_controlmem_0_ARBURST;
output  [1:0] m_axi_controlmem_0_ARLOCK;
output  [3:0] m_axi_controlmem_0_ARCACHE;
output  [2:0] m_axi_controlmem_0_ARPROT;
output  [3:0] m_axi_controlmem_0_ARQOS;
output  [3:0] m_axi_controlmem_0_ARREGION;
output  [0:0] m_axi_controlmem_0_ARUSER;
input   m_axi_controlmem_0_RVALID;
output   m_axi_controlmem_0_RREADY;
input  [31:0] m_axi_controlmem_0_RDATA;
input   m_axi_controlmem_0_RLAST;
input  [0:0] m_axi_controlmem_0_RID;
input  [8:0] m_axi_controlmem_0_RFIFONUM;
input  [0:0] m_axi_controlmem_0_RUSER;
input  [1:0] m_axi_controlmem_0_RRESP;
input   m_axi_controlmem_0_BVALID;
output   m_axi_controlmem_0_BREADY;
input  [1:0] m_axi_controlmem_0_BRESP;
input  [0:0] m_axi_controlmem_0_BID;
input  [0:0] m_axi_controlmem_0_BUSER;
input  [61:0] sext_ln160;
input  [63:0] sums;
input  [63:0] sums_1;
input  [63:0] sums_2;
input  [63:0] sums_3;
input  [63:0] sums_4;
input  [63:0] sums_5;

reg ap_idle;
reg m_axi_controlmem_0_WVALID;
reg[31:0] m_axi_controlmem_0_WDATA;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln160_fu_148_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] icmp_ln160_reg_229;
reg    ap_block_state2_io_grp1;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage1_subdone;
reg    controlmem_blk_n_W;
wire    ap_block_pp0_stage1_grp1;
wire    ap_block_pp0_stage0_grp2;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] trunc_ln160_fu_192_p1;
reg   [31:0] trunc_ln160_reg_233;
reg   [31:0] trunc_ln160_1_reg_238;
reg    ap_block_pp0_stage1_11001_grp1;
wire    ap_block_pp0_stage1_01001_grp1;
reg    ap_block_pp0_stage0_11001_grp2;
wire    ap_block_pp0_stage0_01001_grp2;
reg   [2:0] i_fu_82;
wire   [2:0] add_ln160_fu_154_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_2;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage0_grp0;
wire   [63:0] tmp_1_fu_160_p13;
wire   [63:0] tmp_1_fu_160_p15;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [2:0] tmp_1_fu_160_p1;
wire   [2:0] tmp_1_fu_160_p3;
wire   [2:0] tmp_1_fu_160_p5;
wire   [2:0] tmp_1_fu_160_p7;
wire  signed [2:0] tmp_1_fu_160_p9;
wire  signed [2:0] tmp_1_fu_160_p11;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 i_fu_82 = 3'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) lesion_accel_sparsemux_13_3_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 64 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 64 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 64 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 64 ))
sparsemux_13_3_64_1_1_U4(
    .din0(sums),
    .din1(sums_1),
    .din2(sums_2),
    .din3(sums_3),
    .din4(sums_4),
    .din5(sums_5),
    .def(tmp_1_fu_160_p13),
    .sel(ap_sig_allocacmp_i_2),
    .dout(tmp_1_fu_160_p15)
);

lesion_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln160_fu_148_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_82 <= add_ln160_fu_154_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_82 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln160_reg_229 <= icmp_ln160_fu_148_p2;
        trunc_ln160_1_reg_238 <= {{tmp_1_fu_160_p15[63:32]}};
        trunc_ln160_reg_233 <= trunc_ln160_fu_192_p1;
    end
end

always @ (*) begin
    if (((icmp_ln160_fu_148_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_2 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_82;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_grp2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln160_reg_229 == 1'd0)))) begin
        controlmem_blk_n_W = m_axi_controlmem_0_WREADY;
    end else begin
        controlmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_controlmem_0_WDATA = trunc_ln160_1_reg_238;
    end else if (((1'b0 == ap_block_pp0_stage1_01001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln160_reg_229 == 1'd0))) begin
        m_axi_controlmem_0_WDATA = trunc_ln160_reg_233;
    end else begin
        m_axi_controlmem_0_WDATA = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001_grp2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln160_reg_229 == 1'd0)))) begin
        m_axi_controlmem_0_WVALID = 1'b1;
    end else begin
        m_axi_controlmem_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln160_fu_154_p2 = (ap_sig_allocacmp_i_2 + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_controlmem_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp2 = ((m_axi_controlmem_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_controlmem_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_01001_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((1'b1 == ap_block_state2_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((1'b1 == ap_block_state2_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_io_grp1 = ((m_axi_controlmem_0_WREADY == 1'b0) & (icmp_ln160_reg_229 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln160_fu_148_p2 = ((ap_sig_allocacmp_i_2 == 3'd6) ? 1'b1 : 1'b0);

assign m_axi_controlmem_0_ARADDR = 64'd0;

assign m_axi_controlmem_0_ARBURST = 2'd0;

assign m_axi_controlmem_0_ARCACHE = 4'd0;

assign m_axi_controlmem_0_ARID = 1'd0;

assign m_axi_controlmem_0_ARLEN = 32'd0;

assign m_axi_controlmem_0_ARLOCK = 2'd0;

assign m_axi_controlmem_0_ARPROT = 3'd0;

assign m_axi_controlmem_0_ARQOS = 4'd0;

assign m_axi_controlmem_0_ARREGION = 4'd0;

assign m_axi_controlmem_0_ARSIZE = 3'd0;

assign m_axi_controlmem_0_ARUSER = 1'd0;

assign m_axi_controlmem_0_ARVALID = 1'b0;

assign m_axi_controlmem_0_AWADDR = 64'd0;

assign m_axi_controlmem_0_AWBURST = 2'd0;

assign m_axi_controlmem_0_AWCACHE = 4'd0;

assign m_axi_controlmem_0_AWID = 1'd0;

assign m_axi_controlmem_0_AWLEN = 32'd0;

assign m_axi_controlmem_0_AWLOCK = 2'd0;

assign m_axi_controlmem_0_AWPROT = 3'd0;

assign m_axi_controlmem_0_AWQOS = 4'd0;

assign m_axi_controlmem_0_AWREGION = 4'd0;

assign m_axi_controlmem_0_AWSIZE = 3'd0;

assign m_axi_controlmem_0_AWUSER = 1'd0;

assign m_axi_controlmem_0_AWVALID = 1'b0;

assign m_axi_controlmem_0_BREADY = 1'b0;

assign m_axi_controlmem_0_RREADY = 1'b0;

assign m_axi_controlmem_0_WID = 1'd0;

assign m_axi_controlmem_0_WLAST = 1'b0;

assign m_axi_controlmem_0_WSTRB = 4'd15;

assign m_axi_controlmem_0_WUSER = 1'd0;

assign tmp_1_fu_160_p13 = 'bx;

assign trunc_ln160_fu_192_p1 = tmp_1_fu_160_p15[31:0];

endmodule //lesion_accel_lesion_accel_Pipeline_VITIS_LOOP_160_24
