// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module lesion_accel_rq (
        ap_clk,
        ap_rst,
        x,
        multiplier,
        shift,
        relu,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [31:0] x;
input  [31:0] multiplier;
input  [31:0] shift;
input  [0:0] relu;
output  [7:0] ap_return;
input   ap_ce;

reg[7:0] ap_return;

reg   [0:0] relu_read_reg_203;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] relu_read_reg_203_pp0_iter1_reg;
reg   [0:0] relu_read_reg_203_pp0_iter2_reg;
reg   [0:0] relu_read_reg_203_pp0_iter3_reg;
reg   [0:0] relu_read_reg_203_pp0_iter4_reg;
reg   [0:0] relu_read_reg_203_pp0_iter5_reg;
reg   [31:0] shift_read_reg_209;
reg   [31:0] shift_read_reg_209_pp0_iter1_reg;
reg   [31:0] shift_read_reg_209_pp0_iter2_reg;
wire   [62:0] trunc_ln8_fu_84_p1;
reg   [62:0] trunc_ln8_reg_225;
reg   [0:0] tmp_reg_231;
reg   [0:0] tmp_reg_231_pp0_iter2_reg;
reg   [0:0] tmp_reg_231_pp0_iter3_reg;
wire   [63:0] shl_ln9_fu_105_p2;
reg   [63:0] shl_ln9_reg_237;
wire   [63:0] add_ln9_1_fu_126_p2;
reg   [63:0] add_ln9_1_reg_242;
wire   [63:0] y_fu_134_p2;
reg   [63:0] y_reg_247;
wire   [63:0] y_1_fu_144_p3;
reg   [63:0] y_1_reg_253;
reg   [63:0] y_1_reg_253_pp0_iter5_reg;
reg   [56:0] tmp_1_reg_258;
wire   [0:0] icmp_ln11_fu_160_p2;
reg   [0:0] icmp_ln11_reg_263;
wire    ap_block_pp0_stage0;
wire   [63:0] grp_fu_70_p2;
wire   [31:0] add_ln9_fu_96_p2;
wire   [63:0] zext_ln9_fu_101_p1;
wire   [62:0] sub_ln9_fu_111_p2;
wire   [62:0] select_ln9_fu_116_p3;
wire   [63:0] zext_ln9_2_fu_122_p1;
wire   [63:0] zext_ln9_1_fu_131_p1;
wire   [63:0] sub_ln10_fu_139_p2;
wire   [63:0] y_2_fu_165_p3;
wire   [63:0] select_ln12_2_fu_171_p3;
wire   [0:0] icmp_ln12_fu_178_p2;
wire   [7:0] select_ln12_fu_184_p3;
wire   [7:0] trunc_ln12_fu_191_p1;
reg    grp_fu_70_ce;
wire   [7:0] select_ln12_1_fu_195_p3;
reg    ap_ce_reg;
reg  signed [31:0] x_int_reg;
reg  signed [31:0] multiplier_int_reg;
reg   [31:0] shift_int_reg;
reg   [0:0] relu_int_reg;
reg   [7:0] ap_return_int_reg;

lesion_accel_mul_32s_32s_64_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32s_32s_64_2_0_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(multiplier_int_reg),
    .din1(x_int_reg),
    .ce(grp_fu_70_ce),
    .dout(grp_fu_70_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        add_ln9_1_reg_242 <= add_ln9_1_fu_126_p2;
        icmp_ln11_reg_263 <= icmp_ln11_fu_160_p2;
        relu_read_reg_203 <= relu_int_reg;
        relu_read_reg_203_pp0_iter1_reg <= relu_read_reg_203;
        relu_read_reg_203_pp0_iter2_reg <= relu_read_reg_203_pp0_iter1_reg;
        relu_read_reg_203_pp0_iter3_reg <= relu_read_reg_203_pp0_iter2_reg;
        relu_read_reg_203_pp0_iter4_reg <= relu_read_reg_203_pp0_iter3_reg;
        relu_read_reg_203_pp0_iter5_reg <= relu_read_reg_203_pp0_iter4_reg;
        shift_read_reg_209 <= shift_int_reg;
        shift_read_reg_209_pp0_iter1_reg <= shift_read_reg_209;
        shift_read_reg_209_pp0_iter2_reg <= shift_read_reg_209_pp0_iter1_reg;
        shl_ln9_reg_237 <= shl_ln9_fu_105_p2;
        tmp_1_reg_258 <= {{y_1_fu_144_p3[63:7]}};
        tmp_reg_231 <= grp_fu_70_p2[32'd63];
        tmp_reg_231_pp0_iter2_reg <= tmp_reg_231;
        tmp_reg_231_pp0_iter3_reg <= tmp_reg_231_pp0_iter2_reg;
        trunc_ln8_reg_225 <= trunc_ln8_fu_84_p1;
        y_1_reg_253 <= y_1_fu_144_p3;
        y_1_reg_253_pp0_iter5_reg <= y_1_reg_253;
        y_reg_247 <= y_fu_134_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= select_ln12_1_fu_195_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        multiplier_int_reg <= multiplier;
        relu_int_reg <= relu;
        shift_int_reg <= shift;
        x_int_reg <= x;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = select_ln12_1_fu_195_p3;
    end else begin
        ap_return = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_70_ce = 1'b1;
    end else begin
        grp_fu_70_ce = 1'b0;
    end
end

assign add_ln9_1_fu_126_p2 = (zext_ln9_2_fu_122_p1 + shl_ln9_reg_237);

assign add_ln9_fu_96_p2 = ($signed(shift_read_reg_209) + $signed(32'd4294967295));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign icmp_ln11_fu_160_p2 = (($signed(tmp_1_reg_258) > $signed(57'd0)) ? 1'b1 : 1'b0);

assign icmp_ln12_fu_178_p2 = (($signed(y_2_fu_165_p3) < $signed(select_ln12_2_fu_171_p3)) ? 1'b1 : 1'b0);

assign select_ln12_1_fu_195_p3 = ((icmp_ln12_fu_178_p2[0:0] == 1'b1) ? select_ln12_fu_184_p3 : trunc_ln12_fu_191_p1);

assign select_ln12_2_fu_171_p3 = ((relu_read_reg_203_pp0_iter5_reg[0:0] == 1'b1) ? 64'd0 : 64'd18446744073709551488);

assign select_ln12_fu_184_p3 = ((relu_read_reg_203_pp0_iter5_reg[0:0] == 1'b1) ? 8'd0 : 8'd128);

assign select_ln9_fu_116_p3 = ((tmp_reg_231[0:0] == 1'b1) ? sub_ln9_fu_111_p2 : trunc_ln8_reg_225);

assign shl_ln9_fu_105_p2 = 64'd1 << zext_ln9_fu_101_p1;

assign sub_ln10_fu_139_p2 = (64'd0 - y_reg_247);

assign sub_ln9_fu_111_p2 = (63'd0 - trunc_ln8_reg_225);

assign trunc_ln12_fu_191_p1 = y_2_fu_165_p3[7:0];

assign trunc_ln8_fu_84_p1 = grp_fu_70_p2[62:0];

assign y_1_fu_144_p3 = ((tmp_reg_231_pp0_iter3_reg[0:0] == 1'b1) ? sub_ln10_fu_139_p2 : y_reg_247);

assign y_2_fu_165_p3 = ((icmp_ln11_reg_263[0:0] == 1'b1) ? 64'd127 : y_1_reg_253_pp0_iter5_reg);

assign y_fu_134_p2 = $signed(add_ln9_1_reg_242) >>> zext_ln9_1_fu_131_p1;

assign zext_ln9_1_fu_131_p1 = shift_read_reg_209_pp0_iter2_reg;

assign zext_ln9_2_fu_122_p1 = select_ln9_fu_116_p3;

assign zext_ln9_fu_101_p1 = add_ln9_fu_96_p2;

endmodule //lesion_accel_rq
