// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module lesion_accel_convolution_Pipeline_VITIS_LOOP_37_7_VITIS_LOOP_38_8_VITIS_LOOP_39_9 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY,
        m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY,
        m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY,
        m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID,
        m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA,
        m_axi_gmem_0_RLAST,
        m_axi_gmem_0_RID,
        m_axi_gmem_0_RFIFONUM,
        m_axi_gmem_0_RUSER,
        m_axi_gmem_0_RRESP,
        m_axi_gmem_0_BVALID,
        m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP,
        m_axi_gmem_0_BID,
        m_axi_gmem_0_BUSER,
        tmp_18,
        add_ln38,
        bound,
        ic,
        ci,
        sext_ln25_6,
        sext_ln27,
        sext_ln25_5,
        sext_ln25_1,
        pixels_address0,
        pixels_ce0,
        pixels_we0,
        pixels_d0,
        pixels_1_address0,
        pixels_1_ce0,
        pixels_1_we0,
        pixels_1_d0,
        pixels_2_address0,
        pixels_2_ce0,
        pixels_2_we0,
        pixels_2_d0,
        pixels_3_address0,
        pixels_3_ce0,
        pixels_3_we0,
        pixels_3_d0,
        pixels_4_address0,
        pixels_4_ce0,
        pixels_4_we0,
        pixels_4_d0,
        pixels_5_address0,
        pixels_5_ce0,
        pixels_5_we0,
        pixels_5_d0,
        pixels_6_address0,
        pixels_6_ce0,
        pixels_6_we0,
        pixels_6_d0,
        pixels_7_address0,
        pixels_7_ce0,
        pixels_7_we0,
        pixels_7_d0,
        zext_ln27_1,
        sext_ln25,
        sext_ln25_2,
        sext_ln43,
        mem,
        grp_fu_2116_p_din0,
        grp_fu_2116_p_din1,
        grp_fu_2116_p_dout0,
        grp_fu_2116_p_ce,
        grp_fu_2120_p_din0,
        grp_fu_2120_p_din1,
        grp_fu_2120_p_dout0,
        grp_fu_2120_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_0_AWVALID;
input   m_axi_gmem_0_AWREADY;
output  [63:0] m_axi_gmem_0_AWADDR;
output  [0:0] m_axi_gmem_0_AWID;
output  [31:0] m_axi_gmem_0_AWLEN;
output  [2:0] m_axi_gmem_0_AWSIZE;
output  [1:0] m_axi_gmem_0_AWBURST;
output  [1:0] m_axi_gmem_0_AWLOCK;
output  [3:0] m_axi_gmem_0_AWCACHE;
output  [2:0] m_axi_gmem_0_AWPROT;
output  [3:0] m_axi_gmem_0_AWQOS;
output  [3:0] m_axi_gmem_0_AWREGION;
output  [0:0] m_axi_gmem_0_AWUSER;
output   m_axi_gmem_0_WVALID;
input   m_axi_gmem_0_WREADY;
output  [7:0] m_axi_gmem_0_WDATA;
output  [0:0] m_axi_gmem_0_WSTRB;
output   m_axi_gmem_0_WLAST;
output  [0:0] m_axi_gmem_0_WID;
output  [0:0] m_axi_gmem_0_WUSER;
output   m_axi_gmem_0_ARVALID;
input   m_axi_gmem_0_ARREADY;
output  [63:0] m_axi_gmem_0_ARADDR;
output  [0:0] m_axi_gmem_0_ARID;
output  [31:0] m_axi_gmem_0_ARLEN;
output  [2:0] m_axi_gmem_0_ARSIZE;
output  [1:0] m_axi_gmem_0_ARBURST;
output  [1:0] m_axi_gmem_0_ARLOCK;
output  [3:0] m_axi_gmem_0_ARCACHE;
output  [2:0] m_axi_gmem_0_ARPROT;
output  [3:0] m_axi_gmem_0_ARQOS;
output  [3:0] m_axi_gmem_0_ARREGION;
output  [0:0] m_axi_gmem_0_ARUSER;
input   m_axi_gmem_0_RVALID;
output   m_axi_gmem_0_RREADY;
input  [7:0] m_axi_gmem_0_RDATA;
input   m_axi_gmem_0_RLAST;
input  [0:0] m_axi_gmem_0_RID;
input  [12:0] m_axi_gmem_0_RFIFONUM;
input  [0:0] m_axi_gmem_0_RUSER;
input  [1:0] m_axi_gmem_0_RRESP;
input   m_axi_gmem_0_BVALID;
output   m_axi_gmem_0_BREADY;
input  [1:0] m_axi_gmem_0_BRESP;
input  [0:0] m_axi_gmem_0_BID;
input  [0:0] m_axi_gmem_0_BUSER;
input  [65:0] tmp_18;
input  [31:0] add_ln38;
input  [62:0] bound;
input  [30:0] ic;
input  [31:0] ci;
input  [31:0] sext_ln25_6;
input  [32:0] sext_ln27;
input  [31:0] sext_ln25_5;
input  [31:0] sext_ln25_1;
output  [6:0] pixels_address0;
output   pixels_ce0;
output   pixels_we0;
output  [7:0] pixels_d0;
output  [6:0] pixels_1_address0;
output   pixels_1_ce0;
output   pixels_1_we0;
output  [7:0] pixels_1_d0;
output  [6:0] pixels_2_address0;
output   pixels_2_ce0;
output   pixels_2_we0;
output  [7:0] pixels_2_d0;
output  [6:0] pixels_3_address0;
output   pixels_3_ce0;
output   pixels_3_we0;
output  [7:0] pixels_3_d0;
output  [6:0] pixels_4_address0;
output   pixels_4_ce0;
output   pixels_4_we0;
output  [7:0] pixels_4_d0;
output  [6:0] pixels_5_address0;
output   pixels_5_ce0;
output   pixels_5_we0;
output  [7:0] pixels_5_d0;
output  [6:0] pixels_6_address0;
output   pixels_6_ce0;
output   pixels_6_we0;
output  [7:0] pixels_6_d0;
output  [6:0] pixels_7_address0;
output   pixels_7_ce0;
output   pixels_7_we0;
output  [7:0] pixels_7_d0;
input  [30:0] zext_ln27_1;
input  [30:0] sext_ln25;
input  [31:0] sext_ln25_2;
input  [31:0] sext_ln43;
input  [63:0] mem;
output  [31:0] grp_fu_2116_p_din0;
output  [31:0] grp_fu_2116_p_din1;
input  [61:0] grp_fu_2116_p_dout0;
output   grp_fu_2116_p_ce;
output  [63:0] grp_fu_2120_p_din0;
output  [31:0] grp_fu_2120_p_din1;
input  [63:0] grp_fu_2120_p_dout0;
output   grp_fu_2120_p_ce;

reg ap_idle;
reg m_axi_gmem_0_ARVALID;
reg m_axi_gmem_0_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln37_reg_914;
reg   [0:0] icmp_ln37_reg_914_pp0_iter11_reg;
reg   [0:0] and_ln42_1_reg_1002;
reg   [0:0] and_ln42_1_reg_1002_pp0_iter11_reg;
reg    ap_predicate_op135_readreq_state13;
reg    ap_block_state13_io;
reg   [0:0] icmp_ln37_reg_914_pp0_iter19_reg;
reg   [0:0] and_ln42_1_reg_1002_pp0_iter19_reg;
reg    ap_predicate_op143_read_state21;
reg    ap_block_state21_pp0_stage0_iter20;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln37_fu_453_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_blk_n_AR;
wire    ap_block_pp0_stage0;
reg    gmem_blk_n_R;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001;
wire  signed [63:0] sext_ln43_cast_fu_385_p1;
reg  signed [63:0] sext_ln43_cast_reg_864;
wire  signed [32:0] sext_ln25_cast_fu_389_p1;
reg  signed [32:0] sext_ln25_cast_reg_869;
wire   [32:0] zext_ln27_1_cast_fu_393_p1;
reg   [32:0] zext_ln27_1_cast_reg_874;
wire  signed [63:0] sext_ln25_1_cast_fu_397_p1;
reg  signed [63:0] sext_ln25_1_cast_reg_879;
wire  signed [33:0] sext_ln25_5_cast_fu_401_p1;
reg  signed [33:0] sext_ln25_5_cast_reg_884;
wire  signed [33:0] sext_ln27_cast_fu_405_p1;
reg  signed [33:0] sext_ln27_cast_reg_889;
wire  signed [61:0] sext_ln25_6_cast_fu_409_p1;
reg  signed [61:0] sext_ln25_6_cast_reg_894;
wire   [31:0] ic_cast_fu_413_p1;
reg   [31:0] ic_cast_reg_899;
wire   [63:0] bound_cast_fu_417_p1;
reg   [63:0] bound_cast_reg_904;
wire  signed [32:0] sext_ln25_2_cast_fu_421_p1;
reg  signed [32:0] sext_ln25_2_cast_reg_909;
reg   [0:0] icmp_ln37_reg_914_pp0_iter2_reg;
reg   [0:0] icmp_ln37_reg_914_pp0_iter3_reg;
reg   [0:0] icmp_ln37_reg_914_pp0_iter4_reg;
reg   [0:0] icmp_ln37_reg_914_pp0_iter5_reg;
reg   [0:0] icmp_ln37_reg_914_pp0_iter6_reg;
reg   [0:0] icmp_ln37_reg_914_pp0_iter7_reg;
reg   [0:0] icmp_ln37_reg_914_pp0_iter8_reg;
reg   [0:0] icmp_ln37_reg_914_pp0_iter9_reg;
reg   [0:0] icmp_ln37_reg_914_pp0_iter10_reg;
reg   [0:0] icmp_ln37_reg_914_pp0_iter12_reg;
reg   [0:0] icmp_ln37_reg_914_pp0_iter13_reg;
reg   [0:0] icmp_ln37_reg_914_pp0_iter14_reg;
reg   [0:0] icmp_ln37_reg_914_pp0_iter15_reg;
reg   [0:0] icmp_ln37_reg_914_pp0_iter16_reg;
reg   [0:0] icmp_ln37_reg_914_pp0_iter17_reg;
reg   [0:0] icmp_ln37_reg_914_pp0_iter18_reg;
reg   [0:0] icmp_ln37_reg_914_pp0_iter20_reg;
wire   [0:0] icmp_ln38_fu_481_p2;
reg   [0:0] icmp_ln38_reg_918;
reg   [0:0] icmp_ln38_reg_918_pp0_iter3_reg;
wire   [0:0] icmp_ln39_1_fu_486_p2;
reg   [0:0] icmp_ln39_1_reg_925;
wire   [2:0] trunc_ln37_fu_503_p1;
reg   [2:0] trunc_ln37_reg_930;
reg   [2:0] trunc_ln37_reg_930_pp0_iter3_reg;
reg   [2:0] trunc_ln37_reg_930_pp0_iter4_reg;
reg   [2:0] trunc_ln37_reg_930_pp0_iter5_reg;
reg   [2:0] trunc_ln37_reg_930_pp0_iter6_reg;
reg   [2:0] trunc_ln37_reg_930_pp0_iter7_reg;
reg   [2:0] trunc_ln37_reg_930_pp0_iter8_reg;
reg   [2:0] trunc_ln37_reg_930_pp0_iter9_reg;
reg   [2:0] trunc_ln37_reg_930_pp0_iter10_reg;
reg   [2:0] trunc_ln37_reg_930_pp0_iter11_reg;
reg   [2:0] trunc_ln37_reg_930_pp0_iter12_reg;
reg   [2:0] trunc_ln37_reg_930_pp0_iter13_reg;
reg   [2:0] trunc_ln37_reg_930_pp0_iter14_reg;
reg   [2:0] trunc_ln37_reg_930_pp0_iter15_reg;
reg   [2:0] trunc_ln37_reg_930_pp0_iter16_reg;
reg   [2:0] trunc_ln37_reg_930_pp0_iter17_reg;
reg   [2:0] trunc_ln37_reg_930_pp0_iter18_reg;
reg   [2:0] trunc_ln37_reg_930_pp0_iter19_reg;
reg   [2:0] trunc_ln37_reg_930_pp0_iter20_reg;
wire   [31:0] add_ln42_fu_507_p2;
reg   [31:0] add_ln42_reg_934;
wire   [0:0] select_ln37_1_fu_566_p3;
reg   [0:0] select_ln37_1_reg_940;
wire   [6:0] select_ln38_fu_577_p3;
reg   [6:0] select_ln38_reg_945;
reg   [6:0] select_ln38_reg_945_pp0_iter4_reg;
wire   [61:0] zext_ln42_fu_585_p1;
wire   [0:0] icmp_ln42_fu_589_p2;
reg   [0:0] icmp_ln42_reg_956;
reg   [0:0] icmp_ln42_reg_956_pp0_iter4_reg;
wire   [30:0] select_ln38_1_fu_620_p3;
reg   [30:0] select_ln38_1_reg_961;
reg   [61:0] mul_ln43_reg_966;
wire   [3:0] trunc_ln42_fu_627_p1;
reg   [3:0] trunc_ln42_reg_971;
wire   [5:0] trunc_ln42_1_fu_631_p1;
reg   [5:0] trunc_ln42_1_reg_976;
wire  signed [32:0] add_ln41_1_fu_642_p2;
reg  signed [32:0] add_ln41_1_reg_981;
reg  signed [32:0] add_ln41_1_reg_981_pp0_iter5_reg;
reg  signed [32:0] add_ln41_1_reg_981_pp0_iter6_reg;
reg  signed [32:0] add_ln41_1_reg_981_pp0_iter7_reg;
reg  signed [32:0] add_ln41_1_reg_981_pp0_iter8_reg;
reg  signed [32:0] add_ln41_1_reg_981_pp0_iter9_reg;
reg  signed [32:0] add_ln41_1_reg_981_pp0_iter10_reg;
wire   [0:0] icmp_ln42_3_fu_648_p2;
reg   [0:0] icmp_ln42_3_reg_987;
wire  signed [63:0] add_ln43_fu_735_p2;
reg  signed [63:0] add_ln43_reg_992;
wire   [6:0] add_ln42_1_fu_741_p2;
reg   [6:0] add_ln42_1_reg_997;
reg   [6:0] add_ln42_1_reg_997_pp0_iter6_reg;
reg   [6:0] add_ln42_1_reg_997_pp0_iter7_reg;
reg   [6:0] add_ln42_1_reg_997_pp0_iter8_reg;
reg   [6:0] add_ln42_1_reg_997_pp0_iter9_reg;
reg   [6:0] add_ln42_1_reg_997_pp0_iter10_reg;
reg   [6:0] add_ln42_1_reg_997_pp0_iter11_reg;
reg   [6:0] add_ln42_1_reg_997_pp0_iter12_reg;
reg   [6:0] add_ln42_1_reg_997_pp0_iter13_reg;
reg   [6:0] add_ln42_1_reg_997_pp0_iter14_reg;
reg   [6:0] add_ln42_1_reg_997_pp0_iter15_reg;
reg   [6:0] add_ln42_1_reg_997_pp0_iter16_reg;
reg   [6:0] add_ln42_1_reg_997_pp0_iter17_reg;
reg   [6:0] add_ln42_1_reg_997_pp0_iter18_reg;
reg   [6:0] add_ln42_1_reg_997_pp0_iter19_reg;
reg   [6:0] add_ln42_1_reg_997_pp0_iter20_reg;
wire   [0:0] and_ln42_1_fu_768_p2;
reg   [0:0] and_ln42_1_reg_1002_pp0_iter6_reg;
reg   [0:0] and_ln42_1_reg_1002_pp0_iter7_reg;
reg   [0:0] and_ln42_1_reg_1002_pp0_iter8_reg;
reg   [0:0] and_ln42_1_reg_1002_pp0_iter9_reg;
reg   [0:0] and_ln42_1_reg_1002_pp0_iter10_reg;
reg   [0:0] and_ln42_1_reg_1002_pp0_iter12_reg;
reg   [0:0] and_ln42_1_reg_1002_pp0_iter13_reg;
reg   [0:0] and_ln42_1_reg_1002_pp0_iter14_reg;
reg   [0:0] and_ln42_1_reg_1002_pp0_iter15_reg;
reg   [0:0] and_ln42_1_reg_1002_pp0_iter16_reg;
reg   [0:0] and_ln42_1_reg_1002_pp0_iter17_reg;
reg   [0:0] and_ln42_1_reg_1002_pp0_iter18_reg;
reg   [0:0] and_ln42_1_reg_1002_pp0_iter20_reg;
reg   [63:0] mul_ln43_1_reg_1006;
wire   [63:0] add_ln43_2_fu_774_p2;
reg   [63:0] add_ln43_2_reg_1011;
reg   [63:0] gmem_addr_reg_1016;
reg   [7:0] gmem_addr_read_reg_1022;
reg    ap_condition_exit_pp0_iter3_stage0;
reg   [7:0] ap_phi_mux_cond77_phi_fu_362_p4;
reg   [7:0] ap_phi_reg_pp0_iter21_cond77_reg_358;
wire   [7:0] ap_phi_reg_pp0_iter0_cond77_reg_358;
reg   [7:0] ap_phi_reg_pp0_iter1_cond77_reg_358;
reg   [7:0] ap_phi_reg_pp0_iter2_cond77_reg_358;
reg   [7:0] ap_phi_reg_pp0_iter3_cond77_reg_358;
reg   [7:0] ap_phi_reg_pp0_iter4_cond77_reg_358;
reg   [7:0] ap_phi_reg_pp0_iter5_cond77_reg_358;
reg   [7:0] ap_phi_reg_pp0_iter6_cond77_reg_358;
reg   [7:0] ap_phi_reg_pp0_iter7_cond77_reg_358;
reg   [7:0] ap_phi_reg_pp0_iter8_cond77_reg_358;
reg   [7:0] ap_phi_reg_pp0_iter9_cond77_reg_358;
reg   [7:0] ap_phi_reg_pp0_iter10_cond77_reg_358;
reg   [7:0] ap_phi_reg_pp0_iter11_cond77_reg_358;
reg   [7:0] ap_phi_reg_pp0_iter12_cond77_reg_358;
reg   [7:0] ap_phi_reg_pp0_iter13_cond77_reg_358;
reg   [7:0] ap_phi_reg_pp0_iter14_cond77_reg_358;
reg   [7:0] ap_phi_reg_pp0_iter15_cond77_reg_358;
reg   [7:0] ap_phi_reg_pp0_iter16_cond77_reg_358;
reg   [7:0] ap_phi_reg_pp0_iter17_cond77_reg_358;
reg   [7:0] ap_phi_reg_pp0_iter18_cond77_reg_358;
reg   [7:0] ap_phi_reg_pp0_iter19_cond77_reg_358;
reg   [7:0] ap_phi_reg_pp0_iter20_cond77_reg_358;
wire   [63:0] zext_ln42_2_fu_797_p1;
wire   [63:0] add_ln43_3_fu_786_p2;
reg   [6:0] x_fu_138;
wire   [6:0] add_ln39_fu_593_p2;
wire    ap_loop_init;
reg   [30:0] y_fu_142;
reg   [63:0] indvar_flatten_fu_146;
wire   [63:0] select_ln38_2_fu_536_p3;
reg   [3:0] c_fu_150;
wire   [3:0] select_ln37_2_fu_491_p3;
reg   [65:0] indvar_flatten20_fu_154;
wire   [65:0] add_ln37_1_fu_458_p2;
reg    pixels_6_we0_local;
reg    pixels_6_ce0_local;
reg    pixels_5_we0_local;
reg    pixels_5_ce0_local;
reg    pixels_4_we0_local;
reg    pixels_4_ce0_local;
reg    pixels_3_we0_local;
reg    pixels_3_ce0_local;
reg    pixels_2_we0_local;
reg    pixels_2_ce0_local;
reg    pixels_1_we0_local;
reg    pixels_1_ce0_local;
reg    pixels_we0_local;
reg    pixels_ce0_local;
reg    pixels_7_we0_local;
reg    pixels_7_ce0_local;
wire   [3:0] add_ln37_fu_475_p2;
wire   [31:0] zext_ln37_fu_499_p1;
wire   [63:0] add_ln38_2_fu_530_p2;
wire   [31:0] zext_ln39_fu_557_p1;
wire   [0:0] icmp_ln39_fu_561_p2;
wire   [0:0] or_ln38_fu_572_p2;
wire   [30:0] select_ln37_fu_607_p3;
wire   [30:0] add_ln38_1_fu_614_p2;
wire   [32:0] zext_ln40_fu_635_p1;
wire   [32:0] sub_ln41_fu_638_p2;
wire   [6:0] p_shl_fu_666_p3;
wire   [6:0] p_shl1_fu_673_p3;
wire   [33:0] zext_ln38_fu_686_p1;
wire  signed [33:0] add_ln41_fu_689_p2;
wire   [0:0] icmp_ln42_2_fu_706_p2;
wire   [0:0] xor_ln42_2_fu_711_p2;
wire   [0:0] xor_ln42_1_fu_658_p2;
wire   [0:0] or_ln42_fu_717_p2;
wire   [0:0] tmp_fu_698_p3;
wire   [0:0] or_ln42_1_fu_723_p2;
wire  signed [63:0] sext_ln42_fu_694_p1;
wire   [63:0] zext_ln42_1_fu_663_p1;
wire   [6:0] add_ln42_2_fu_680_p2;
wire  signed [33:0] sext_ln42_2_fu_746_p1;
wire   [0:0] tmp_21_fu_749_p3;
wire   [0:0] xor_ln42_fu_729_p2;
wire   [0:0] and_ln42_fu_763_p2;
wire   [0:0] xor_ln42_3_fu_757_p2;
wire  signed [63:0] sext_ln42_1_fu_778_p1;
wire   [63:0] add_ln43_1_fu_781_p2;
reg    grp_fu_377_ce;
reg    grp_fu_381_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 x_fu_138 = 7'd0;
#0 y_fu_142 = 31'd0;
#0 indvar_flatten_fu_146 = 64'd0;
#0 c_fu_150 = 4'd0;
#0 indvar_flatten20_fu_154 = 66'd0;
#0 ap_done_reg = 1'b0;
end

lesion_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter20_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter3_stage0)) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln37_reg_914_pp0_iter5_reg == 1'd0) & (1'd0 == and_ln42_1_reg_1002))) begin
            ap_phi_reg_pp0_iter7_cond77_reg_358 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter7_cond77_reg_358 <= ap_phi_reg_pp0_iter6_cond77_reg_358;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            c_fu_150 <= 4'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln37_reg_914 == 1'd0))) begin
            c_fu_150 <= select_ln37_2_fu_491_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten20_fu_154 <= 66'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln37_fu_453_p2 == 1'd0))) begin
            indvar_flatten20_fu_154 <= add_ln37_1_fu_458_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            indvar_flatten_fu_146 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln37_reg_914 == 1'd0))) begin
            indvar_flatten_fu_146 <= select_ln38_2_fu_536_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            x_fu_138 <= 7'd0;
        end else if (((icmp_ln37_reg_914_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            x_fu_138 <= add_ln39_fu_593_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            y_fu_142 <= 31'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            y_fu_142 <= select_ln38_1_fu_620_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln41_1_reg_981 <= add_ln41_1_fu_642_p2;
        add_ln41_1_reg_981_pp0_iter10_reg <= add_ln41_1_reg_981_pp0_iter9_reg;
        add_ln41_1_reg_981_pp0_iter5_reg <= add_ln41_1_reg_981;
        add_ln41_1_reg_981_pp0_iter6_reg <= add_ln41_1_reg_981_pp0_iter5_reg;
        add_ln41_1_reg_981_pp0_iter7_reg <= add_ln41_1_reg_981_pp0_iter6_reg;
        add_ln41_1_reg_981_pp0_iter8_reg <= add_ln41_1_reg_981_pp0_iter7_reg;
        add_ln41_1_reg_981_pp0_iter9_reg <= add_ln41_1_reg_981_pp0_iter8_reg;
        add_ln42_1_reg_997 <= add_ln42_1_fu_741_p2;
        add_ln42_1_reg_997_pp0_iter10_reg <= add_ln42_1_reg_997_pp0_iter9_reg;
        add_ln42_1_reg_997_pp0_iter11_reg <= add_ln42_1_reg_997_pp0_iter10_reg;
        add_ln42_1_reg_997_pp0_iter12_reg <= add_ln42_1_reg_997_pp0_iter11_reg;
        add_ln42_1_reg_997_pp0_iter13_reg <= add_ln42_1_reg_997_pp0_iter12_reg;
        add_ln42_1_reg_997_pp0_iter14_reg <= add_ln42_1_reg_997_pp0_iter13_reg;
        add_ln42_1_reg_997_pp0_iter15_reg <= add_ln42_1_reg_997_pp0_iter14_reg;
        add_ln42_1_reg_997_pp0_iter16_reg <= add_ln42_1_reg_997_pp0_iter15_reg;
        add_ln42_1_reg_997_pp0_iter17_reg <= add_ln42_1_reg_997_pp0_iter16_reg;
        add_ln42_1_reg_997_pp0_iter18_reg <= add_ln42_1_reg_997_pp0_iter17_reg;
        add_ln42_1_reg_997_pp0_iter19_reg <= add_ln42_1_reg_997_pp0_iter18_reg;
        add_ln42_1_reg_997_pp0_iter20_reg <= add_ln42_1_reg_997_pp0_iter19_reg;
        add_ln42_1_reg_997_pp0_iter6_reg <= add_ln42_1_reg_997;
        add_ln42_1_reg_997_pp0_iter7_reg <= add_ln42_1_reg_997_pp0_iter6_reg;
        add_ln42_1_reg_997_pp0_iter8_reg <= add_ln42_1_reg_997_pp0_iter7_reg;
        add_ln42_1_reg_997_pp0_iter9_reg <= add_ln42_1_reg_997_pp0_iter8_reg;
        add_ln42_reg_934 <= add_ln42_fu_507_p2;
        add_ln43_2_reg_1011 <= add_ln43_2_fu_774_p2;
        add_ln43_reg_992 <= add_ln43_fu_735_p2;
        and_ln42_1_reg_1002 <= and_ln42_1_fu_768_p2;
        and_ln42_1_reg_1002_pp0_iter10_reg <= and_ln42_1_reg_1002_pp0_iter9_reg;
        and_ln42_1_reg_1002_pp0_iter11_reg <= and_ln42_1_reg_1002_pp0_iter10_reg;
        and_ln42_1_reg_1002_pp0_iter12_reg <= and_ln42_1_reg_1002_pp0_iter11_reg;
        and_ln42_1_reg_1002_pp0_iter13_reg <= and_ln42_1_reg_1002_pp0_iter12_reg;
        and_ln42_1_reg_1002_pp0_iter14_reg <= and_ln42_1_reg_1002_pp0_iter13_reg;
        and_ln42_1_reg_1002_pp0_iter15_reg <= and_ln42_1_reg_1002_pp0_iter14_reg;
        and_ln42_1_reg_1002_pp0_iter16_reg <= and_ln42_1_reg_1002_pp0_iter15_reg;
        and_ln42_1_reg_1002_pp0_iter17_reg <= and_ln42_1_reg_1002_pp0_iter16_reg;
        and_ln42_1_reg_1002_pp0_iter18_reg <= and_ln42_1_reg_1002_pp0_iter17_reg;
        and_ln42_1_reg_1002_pp0_iter19_reg <= and_ln42_1_reg_1002_pp0_iter18_reg;
        and_ln42_1_reg_1002_pp0_iter20_reg <= and_ln42_1_reg_1002_pp0_iter19_reg;
        and_ln42_1_reg_1002_pp0_iter6_reg <= and_ln42_1_reg_1002;
        and_ln42_1_reg_1002_pp0_iter7_reg <= and_ln42_1_reg_1002_pp0_iter6_reg;
        and_ln42_1_reg_1002_pp0_iter8_reg <= and_ln42_1_reg_1002_pp0_iter7_reg;
        and_ln42_1_reg_1002_pp0_iter9_reg <= and_ln42_1_reg_1002_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        gmem_addr_read_reg_1022 <= m_axi_gmem_0_RDATA;
        gmem_addr_reg_1016 <= add_ln43_3_fu_786_p2;
        icmp_ln37_reg_914_pp0_iter10_reg <= icmp_ln37_reg_914_pp0_iter9_reg;
        icmp_ln37_reg_914_pp0_iter11_reg <= icmp_ln37_reg_914_pp0_iter10_reg;
        icmp_ln37_reg_914_pp0_iter12_reg <= icmp_ln37_reg_914_pp0_iter11_reg;
        icmp_ln37_reg_914_pp0_iter13_reg <= icmp_ln37_reg_914_pp0_iter12_reg;
        icmp_ln37_reg_914_pp0_iter14_reg <= icmp_ln37_reg_914_pp0_iter13_reg;
        icmp_ln37_reg_914_pp0_iter15_reg <= icmp_ln37_reg_914_pp0_iter14_reg;
        icmp_ln37_reg_914_pp0_iter16_reg <= icmp_ln37_reg_914_pp0_iter15_reg;
        icmp_ln37_reg_914_pp0_iter17_reg <= icmp_ln37_reg_914_pp0_iter16_reg;
        icmp_ln37_reg_914_pp0_iter18_reg <= icmp_ln37_reg_914_pp0_iter17_reg;
        icmp_ln37_reg_914_pp0_iter19_reg <= icmp_ln37_reg_914_pp0_iter18_reg;
        icmp_ln37_reg_914_pp0_iter20_reg <= icmp_ln37_reg_914_pp0_iter19_reg;
        icmp_ln37_reg_914_pp0_iter2_reg <= icmp_ln37_reg_914;
        icmp_ln37_reg_914_pp0_iter3_reg <= icmp_ln37_reg_914_pp0_iter2_reg;
        icmp_ln37_reg_914_pp0_iter4_reg <= icmp_ln37_reg_914_pp0_iter3_reg;
        icmp_ln37_reg_914_pp0_iter5_reg <= icmp_ln37_reg_914_pp0_iter4_reg;
        icmp_ln37_reg_914_pp0_iter6_reg <= icmp_ln37_reg_914_pp0_iter5_reg;
        icmp_ln37_reg_914_pp0_iter7_reg <= icmp_ln37_reg_914_pp0_iter6_reg;
        icmp_ln37_reg_914_pp0_iter8_reg <= icmp_ln37_reg_914_pp0_iter7_reg;
        icmp_ln37_reg_914_pp0_iter9_reg <= icmp_ln37_reg_914_pp0_iter8_reg;
        icmp_ln38_reg_918 <= icmp_ln38_fu_481_p2;
        icmp_ln38_reg_918_pp0_iter3_reg <= icmp_ln38_reg_918;
        icmp_ln39_1_reg_925 <= icmp_ln39_1_fu_486_p2;
        icmp_ln42_3_reg_987 <= icmp_ln42_3_fu_648_p2;
        icmp_ln42_reg_956 <= icmp_ln42_fu_589_p2;
        icmp_ln42_reg_956_pp0_iter4_reg <= icmp_ln42_reg_956;
        mul_ln43_1_reg_1006 <= grp_fu_2120_p_dout0;
        mul_ln43_reg_966 <= grp_fu_2116_p_dout0;
        select_ln37_1_reg_940 <= select_ln37_1_fu_566_p3;
        select_ln38_1_reg_961 <= select_ln38_1_fu_620_p3;
        select_ln38_reg_945 <= select_ln38_fu_577_p3;
        select_ln38_reg_945_pp0_iter4_reg <= select_ln38_reg_945;
        trunc_ln37_reg_930 <= trunc_ln37_fu_503_p1;
        trunc_ln37_reg_930_pp0_iter10_reg <= trunc_ln37_reg_930_pp0_iter9_reg;
        trunc_ln37_reg_930_pp0_iter11_reg <= trunc_ln37_reg_930_pp0_iter10_reg;
        trunc_ln37_reg_930_pp0_iter12_reg <= trunc_ln37_reg_930_pp0_iter11_reg;
        trunc_ln37_reg_930_pp0_iter13_reg <= trunc_ln37_reg_930_pp0_iter12_reg;
        trunc_ln37_reg_930_pp0_iter14_reg <= trunc_ln37_reg_930_pp0_iter13_reg;
        trunc_ln37_reg_930_pp0_iter15_reg <= trunc_ln37_reg_930_pp0_iter14_reg;
        trunc_ln37_reg_930_pp0_iter16_reg <= trunc_ln37_reg_930_pp0_iter15_reg;
        trunc_ln37_reg_930_pp0_iter17_reg <= trunc_ln37_reg_930_pp0_iter16_reg;
        trunc_ln37_reg_930_pp0_iter18_reg <= trunc_ln37_reg_930_pp0_iter17_reg;
        trunc_ln37_reg_930_pp0_iter19_reg <= trunc_ln37_reg_930_pp0_iter18_reg;
        trunc_ln37_reg_930_pp0_iter20_reg <= trunc_ln37_reg_930_pp0_iter19_reg;
        trunc_ln37_reg_930_pp0_iter3_reg <= trunc_ln37_reg_930;
        trunc_ln37_reg_930_pp0_iter4_reg <= trunc_ln37_reg_930_pp0_iter3_reg;
        trunc_ln37_reg_930_pp0_iter5_reg <= trunc_ln37_reg_930_pp0_iter4_reg;
        trunc_ln37_reg_930_pp0_iter6_reg <= trunc_ln37_reg_930_pp0_iter5_reg;
        trunc_ln37_reg_930_pp0_iter7_reg <= trunc_ln37_reg_930_pp0_iter6_reg;
        trunc_ln37_reg_930_pp0_iter8_reg <= trunc_ln37_reg_930_pp0_iter7_reg;
        trunc_ln37_reg_930_pp0_iter9_reg <= trunc_ln37_reg_930_pp0_iter8_reg;
        trunc_ln42_1_reg_976 <= trunc_ln42_1_fu_631_p1;
        trunc_ln42_reg_971 <= trunc_ln42_fu_627_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        bound_cast_reg_904[62 : 0] <= bound_cast_fu_417_p1[62 : 0];
        ic_cast_reg_899[30 : 0] <= ic_cast_fu_413_p1[30 : 0];
        icmp_ln37_reg_914 <= icmp_ln37_fu_453_p2;
        sext_ln25_1_cast_reg_879 <= sext_ln25_1_cast_fu_397_p1;
        sext_ln25_2_cast_reg_909 <= sext_ln25_2_cast_fu_421_p1;
        sext_ln25_5_cast_reg_884 <= sext_ln25_5_cast_fu_401_p1;
        sext_ln25_6_cast_reg_894 <= sext_ln25_6_cast_fu_409_p1;
        sext_ln25_cast_reg_869 <= sext_ln25_cast_fu_389_p1;
        sext_ln27_cast_reg_889 <= sext_ln27_cast_fu_405_p1;
        sext_ln43_cast_reg_864 <= sext_ln43_cast_fu_385_p1;
        zext_ln27_1_cast_reg_874[30 : 0] <= zext_ln27_1_cast_fu_393_p1[30 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter10_cond77_reg_358 <= ap_phi_reg_pp0_iter9_cond77_reg_358;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter11_cond77_reg_358 <= ap_phi_reg_pp0_iter10_cond77_reg_358;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter12_cond77_reg_358 <= ap_phi_reg_pp0_iter11_cond77_reg_358;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter13_cond77_reg_358 <= ap_phi_reg_pp0_iter12_cond77_reg_358;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter14_cond77_reg_358 <= ap_phi_reg_pp0_iter13_cond77_reg_358;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter15_cond77_reg_358 <= ap_phi_reg_pp0_iter14_cond77_reg_358;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter16_cond77_reg_358 <= ap_phi_reg_pp0_iter15_cond77_reg_358;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter17_cond77_reg_358 <= ap_phi_reg_pp0_iter16_cond77_reg_358;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter18_cond77_reg_358 <= ap_phi_reg_pp0_iter17_cond77_reg_358;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter19_cond77_reg_358 <= ap_phi_reg_pp0_iter18_cond77_reg_358;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_cond77_reg_358 <= ap_phi_reg_pp0_iter0_cond77_reg_358;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter20_cond77_reg_358 <= ap_phi_reg_pp0_iter19_cond77_reg_358;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter21_cond77_reg_358 <= ap_phi_reg_pp0_iter20_cond77_reg_358;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter2_cond77_reg_358 <= ap_phi_reg_pp0_iter1_cond77_reg_358;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_cond77_reg_358 <= ap_phi_reg_pp0_iter2_cond77_reg_358;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter4_cond77_reg_358 <= ap_phi_reg_pp0_iter3_cond77_reg_358;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter5_cond77_reg_358 <= ap_phi_reg_pp0_iter4_cond77_reg_358;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter6_cond77_reg_358 <= ap_phi_reg_pp0_iter5_cond77_reg_358;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter8_cond77_reg_358 <= ap_phi_reg_pp0_iter7_cond77_reg_358;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter9_cond77_reg_358 <= ap_phi_reg_pp0_iter8_cond77_reg_358;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln37_fu_453_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln37_reg_914_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter20_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln37_reg_914_pp0_iter20_reg == 1'd0) & (1'd1 == and_ln42_1_reg_1002_pp0_iter20_reg))) begin
        ap_phi_mux_cond77_phi_fu_362_p4 = gmem_addr_read_reg_1022;
    end else begin
        ap_phi_mux_cond77_phi_fu_362_p4 = ap_phi_reg_pp0_iter21_cond77_reg_358;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op135_readreq_state13 == 1'b1))) begin
        gmem_blk_n_AR = m_axi_gmem_0_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op143_read_state21 == 1'b1))) begin
        gmem_blk_n_R = m_axi_gmem_0_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_377_ce = 1'b1;
    end else begin
        grp_fu_377_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_381_ce = 1'b1;
    end else begin
        grp_fu_381_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op135_readreq_state13 == 1'b1))) begin
        m_axi_gmem_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op143_read_state21 == 1'b1))) begin
        m_axi_gmem_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pixels_1_ce0_local = 1'b1;
    end else begin
        pixels_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (trunc_ln37_reg_930_pp0_iter20_reg == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pixels_1_we0_local = 1'b1;
    end else begin
        pixels_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pixels_2_ce0_local = 1'b1;
    end else begin
        pixels_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (trunc_ln37_reg_930_pp0_iter20_reg == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pixels_2_we0_local = 1'b1;
    end else begin
        pixels_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pixels_3_ce0_local = 1'b1;
    end else begin
        pixels_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (trunc_ln37_reg_930_pp0_iter20_reg == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pixels_3_we0_local = 1'b1;
    end else begin
        pixels_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pixels_4_ce0_local = 1'b1;
    end else begin
        pixels_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (trunc_ln37_reg_930_pp0_iter20_reg == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pixels_4_we0_local = 1'b1;
    end else begin
        pixels_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pixels_5_ce0_local = 1'b1;
    end else begin
        pixels_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (trunc_ln37_reg_930_pp0_iter20_reg == 3'd5) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pixels_5_we0_local = 1'b1;
    end else begin
        pixels_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pixels_6_ce0_local = 1'b1;
    end else begin
        pixels_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (trunc_ln37_reg_930_pp0_iter20_reg == 3'd6) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pixels_6_we0_local = 1'b1;
    end else begin
        pixels_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pixels_7_ce0_local = 1'b1;
    end else begin
        pixels_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (trunc_ln37_reg_930_pp0_iter20_reg == 3'd7) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pixels_7_we0_local = 1'b1;
    end else begin
        pixels_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pixels_ce0_local = 1'b1;
    end else begin
        pixels_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (trunc_ln37_reg_930_pp0_iter20_reg == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pixels_we0_local = 1'b1;
    end else begin
        pixels_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln37_1_fu_458_p2 = (indvar_flatten20_fu_154 + 66'd1);

assign add_ln37_fu_475_p2 = (c_fu_150 + 4'd1);

assign add_ln38_1_fu_614_p2 = (select_ln37_fu_607_p3 + 31'd1);

assign add_ln38_2_fu_530_p2 = (indvar_flatten_fu_146 + 64'd1);

assign add_ln39_fu_593_p2 = (select_ln38_fu_577_p3 + 7'd1);

assign add_ln41_1_fu_642_p2 = (zext_ln40_fu_635_p1 + sub_ln41_fu_638_p2);

assign add_ln41_fu_689_p2 = ($signed(zext_ln38_fu_686_p1) + $signed(sext_ln27_cast_reg_889));

assign add_ln42_1_fu_741_p2 = (add_ln42_2_fu_680_p2 + select_ln38_reg_945_pp0_iter4_reg);

assign add_ln42_2_fu_680_p2 = (p_shl_fu_666_p3 + p_shl1_fu_673_p3);

assign add_ln42_fu_507_p2 = (zext_ln37_fu_499_p1 + ic_cast_reg_899);

assign add_ln43_1_fu_781_p2 = ($signed(mul_ln43_1_reg_1006) + $signed(sext_ln42_1_fu_778_p1));

assign add_ln43_2_fu_774_p2 = ($signed(sext_ln43_cast_reg_864) + $signed(mem));

assign add_ln43_3_fu_786_p2 = (add_ln43_2_reg_1011 + add_ln43_1_fu_781_p2);

assign add_ln43_fu_735_p2 = ($signed(sext_ln42_fu_694_p1) + $signed(zext_ln42_1_fu_663_p1));

assign and_ln42_1_fu_768_p2 = (xor_ln42_3_fu_757_p2 & and_ln42_fu_763_p2);

assign and_ln42_fu_763_p2 = (xor_ln42_fu_729_p2 & icmp_ln42_3_reg_987);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b1 == ap_block_state21_pp0_stage0_iter20)) | ((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_block_state13_io)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b1 == ap_block_state21_pp0_stage0_iter20)) | ((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_block_state13_io)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state13_io = ((ap_predicate_op135_readreq_state13 == 1'b1) & (m_axi_gmem_0_ARREADY == 1'b0));
end

always @ (*) begin
    ap_block_state21_pp0_stage0_iter20 = ((ap_predicate_op143_read_state21 == 1'b1) & (m_axi_gmem_0_RVALID == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_phi_reg_pp0_iter0_cond77_reg_358 = 'bx;

always @ (*) begin
    ap_predicate_op135_readreq_state13 = ((1'd1 == and_ln42_1_reg_1002_pp0_iter11_reg) & (icmp_ln37_reg_914_pp0_iter11_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op143_read_state21 = ((icmp_ln37_reg_914_pp0_iter19_reg == 1'd0) & (1'd1 == and_ln42_1_reg_1002_pp0_iter19_reg));
end

assign ap_ready = ap_ready_sig;

assign bound_cast_fu_417_p1 = bound;

assign grp_fu_2116_p_ce = grp_fu_377_ce;

assign grp_fu_2116_p_din0 = zext_ln42_fu_585_p1;

assign grp_fu_2116_p_din1 = sext_ln25_6_cast_reg_894;

assign grp_fu_2120_p_ce = grp_fu_381_ce;

assign grp_fu_2120_p_din0 = add_ln43_reg_992;

assign grp_fu_2120_p_din1 = sext_ln25_1_cast_reg_879;

assign ic_cast_fu_413_p1 = ic;

assign icmp_ln37_fu_453_p2 = ((indvar_flatten20_fu_154 == tmp_18) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_481_p2 = ((indvar_flatten_fu_146 == bound_cast_reg_904) ? 1'b1 : 1'b0);

assign icmp_ln39_1_fu_486_p2 = ((add_ln38 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_561_p2 = ((zext_ln39_fu_557_p1 == add_ln38) ? 1'b1 : 1'b0);

assign icmp_ln42_2_fu_706_p2 = (($signed(add_ln41_fu_689_p2) < $signed(sext_ln25_5_cast_reg_884)) ? 1'b1 : 1'b0);

assign icmp_ln42_3_fu_648_p2 = (($signed(add_ln41_1_fu_642_p2) < $signed(sext_ln25_2_cast_reg_909)) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_589_p2 = (($signed(add_ln42_reg_934) < $signed(ci)) ? 1'b1 : 1'b0);

assign m_axi_gmem_0_ARADDR = gmem_addr_reg_1016;

assign m_axi_gmem_0_ARBURST = 2'd0;

assign m_axi_gmem_0_ARCACHE = 4'd0;

assign m_axi_gmem_0_ARID = 1'd0;

assign m_axi_gmem_0_ARLEN = 64'd1;

assign m_axi_gmem_0_ARLOCK = 2'd0;

assign m_axi_gmem_0_ARPROT = 3'd0;

assign m_axi_gmem_0_ARQOS = 4'd0;

assign m_axi_gmem_0_ARREGION = 4'd0;

assign m_axi_gmem_0_ARSIZE = 3'd0;

assign m_axi_gmem_0_ARUSER = 1'd0;

assign m_axi_gmem_0_AWADDR = 64'd0;

assign m_axi_gmem_0_AWBURST = 2'd0;

assign m_axi_gmem_0_AWCACHE = 4'd0;

assign m_axi_gmem_0_AWID = 1'd0;

assign m_axi_gmem_0_AWLEN = 32'd0;

assign m_axi_gmem_0_AWLOCK = 2'd0;

assign m_axi_gmem_0_AWPROT = 3'd0;

assign m_axi_gmem_0_AWQOS = 4'd0;

assign m_axi_gmem_0_AWREGION = 4'd0;

assign m_axi_gmem_0_AWSIZE = 3'd0;

assign m_axi_gmem_0_AWUSER = 1'd0;

assign m_axi_gmem_0_AWVALID = 1'b0;

assign m_axi_gmem_0_BREADY = 1'b0;

assign m_axi_gmem_0_WDATA = 8'd0;

assign m_axi_gmem_0_WID = 1'd0;

assign m_axi_gmem_0_WLAST = 1'b0;

assign m_axi_gmem_0_WSTRB = 1'd0;

assign m_axi_gmem_0_WUSER = 1'd0;

assign m_axi_gmem_0_WVALID = 1'b0;

assign or_ln38_fu_572_p2 = (select_ln37_1_fu_566_p3 | icmp_ln38_reg_918);

assign or_ln42_1_fu_723_p2 = (tmp_fu_698_p3 | or_ln42_fu_717_p2);

assign or_ln42_fu_717_p2 = (xor_ln42_2_fu_711_p2 | xor_ln42_1_fu_658_p2);

assign p_shl1_fu_673_p3 = {{trunc_ln42_1_reg_976}, {1'd0}};

assign p_shl_fu_666_p3 = {{trunc_ln42_reg_971}, {3'd0}};

assign pixels_1_address0 = zext_ln42_2_fu_797_p1;

assign pixels_1_ce0 = pixels_1_ce0_local;

assign pixels_1_d0 = ap_phi_mux_cond77_phi_fu_362_p4;

assign pixels_1_we0 = pixels_1_we0_local;

assign pixels_2_address0 = zext_ln42_2_fu_797_p1;

assign pixels_2_ce0 = pixels_2_ce0_local;

assign pixels_2_d0 = ap_phi_mux_cond77_phi_fu_362_p4;

assign pixels_2_we0 = pixels_2_we0_local;

assign pixels_3_address0 = zext_ln42_2_fu_797_p1;

assign pixels_3_ce0 = pixels_3_ce0_local;

assign pixels_3_d0 = ap_phi_mux_cond77_phi_fu_362_p4;

assign pixels_3_we0 = pixels_3_we0_local;

assign pixels_4_address0 = zext_ln42_2_fu_797_p1;

assign pixels_4_ce0 = pixels_4_ce0_local;

assign pixels_4_d0 = ap_phi_mux_cond77_phi_fu_362_p4;

assign pixels_4_we0 = pixels_4_we0_local;

assign pixels_5_address0 = zext_ln42_2_fu_797_p1;

assign pixels_5_ce0 = pixels_5_ce0_local;

assign pixels_5_d0 = ap_phi_mux_cond77_phi_fu_362_p4;

assign pixels_5_we0 = pixels_5_we0_local;

assign pixels_6_address0 = zext_ln42_2_fu_797_p1;

assign pixels_6_ce0 = pixels_6_ce0_local;

assign pixels_6_d0 = ap_phi_mux_cond77_phi_fu_362_p4;

assign pixels_6_we0 = pixels_6_we0_local;

assign pixels_7_address0 = zext_ln42_2_fu_797_p1;

assign pixels_7_ce0 = pixels_7_ce0_local;

assign pixels_7_d0 = ap_phi_mux_cond77_phi_fu_362_p4;

assign pixels_7_we0 = pixels_7_we0_local;

assign pixels_address0 = zext_ln42_2_fu_797_p1;

assign pixels_ce0 = pixels_ce0_local;

assign pixels_d0 = ap_phi_mux_cond77_phi_fu_362_p4;

assign pixels_we0 = pixels_we0_local;

assign select_ln37_1_fu_566_p3 = ((icmp_ln38_reg_918[0:0] == 1'b1) ? icmp_ln39_1_reg_925 : icmp_ln39_fu_561_p2);

assign select_ln37_2_fu_491_p3 = ((icmp_ln38_fu_481_p2[0:0] == 1'b1) ? add_ln37_fu_475_p2 : c_fu_150);

assign select_ln37_fu_607_p3 = ((icmp_ln38_reg_918_pp0_iter3_reg[0:0] == 1'b1) ? 31'd0 : y_fu_142);

assign select_ln38_1_fu_620_p3 = ((select_ln37_1_reg_940[0:0] == 1'b1) ? add_ln38_1_fu_614_p2 : select_ln37_fu_607_p3);

assign select_ln38_2_fu_536_p3 = ((icmp_ln38_fu_481_p2[0:0] == 1'b1) ? 64'd1 : add_ln38_2_fu_530_p2);

assign select_ln38_fu_577_p3 = ((or_ln38_fu_572_p2[0:0] == 1'b1) ? 7'd0 : x_fu_138);

assign sext_ln25_1_cast_fu_397_p1 = $signed(sext_ln25_1);

assign sext_ln25_2_cast_fu_421_p1 = $signed(sext_ln25_2);

assign sext_ln25_5_cast_fu_401_p1 = $signed(sext_ln25_5);

assign sext_ln25_6_cast_fu_409_p1 = $signed(sext_ln25_6);

assign sext_ln25_cast_fu_389_p1 = $signed(sext_ln25);

assign sext_ln27_cast_fu_405_p1 = $signed(sext_ln27);

assign sext_ln42_1_fu_778_p1 = add_ln41_1_reg_981_pp0_iter10_reg;

assign sext_ln42_2_fu_746_p1 = add_ln41_1_reg_981;

assign sext_ln42_fu_694_p1 = add_ln41_fu_689_p2;

assign sext_ln43_cast_fu_385_p1 = $signed(sext_ln43);

assign sub_ln41_fu_638_p2 = ($signed(zext_ln27_1_cast_reg_874) - $signed(sext_ln25_cast_reg_869));

assign tmp_21_fu_749_p3 = sext_ln42_2_fu_746_p1[32'd33];

assign tmp_fu_698_p3 = add_ln41_fu_689_p2[32'd33];

assign trunc_ln37_fu_503_p1 = select_ln37_2_fu_491_p3[2:0];

assign trunc_ln42_1_fu_631_p1 = select_ln38_1_fu_620_p3[5:0];

assign trunc_ln42_fu_627_p1 = select_ln38_1_fu_620_p3[3:0];

assign xor_ln42_1_fu_658_p2 = (icmp_ln42_reg_956_pp0_iter4_reg ^ 1'd1);

assign xor_ln42_2_fu_711_p2 = (icmp_ln42_2_fu_706_p2 ^ 1'd1);

assign xor_ln42_3_fu_757_p2 = (tmp_21_fu_749_p3 ^ 1'd1);

assign xor_ln42_fu_729_p2 = (or_ln42_1_fu_723_p2 ^ 1'd1);

assign zext_ln27_1_cast_fu_393_p1 = zext_ln27_1;

assign zext_ln37_fu_499_p1 = select_ln37_2_fu_491_p3;

assign zext_ln38_fu_686_p1 = select_ln38_1_reg_961;

assign zext_ln39_fu_557_p1 = x_fu_138;

assign zext_ln40_fu_635_p1 = select_ln38_reg_945;

assign zext_ln42_1_fu_663_p1 = mul_ln43_reg_966;

assign zext_ln42_2_fu_797_p1 = add_ln42_1_reg_997_pp0_iter20_reg;

assign zext_ln42_fu_585_p1 = add_ln42_reg_934;

always @ (posedge ap_clk) begin
    zext_ln27_1_cast_reg_874[32:31] <= 2'b00;
    ic_cast_reg_899[31] <= 1'b0;
    bound_cast_reg_904[63] <= 1'b0;
end

endmodule //lesion_accel_convolution_Pipeline_VITIS_LOOP_37_7_VITIS_LOOP_38_8_VITIS_LOOP_39_9
